<?php $loginWithEmail=$loginWithEmail ?? false; $identifier=$old['identifier'] ?? $old['email'] ?? ''; ?>
<section class="auth-page"><div class="container auth-grid"><div class="auth-intro stack"><span class="eyebrow">خوش آمدید</span><h1>ادامهٔ مسیر، با یک ورود ساده</h1><p>با شمارهٔ موبایل و رمز عبوری که هنگام عضویت انتخاب کرده‌اید، وارد حساب منتوریس شوید.</p><div class="auth-quote"><span>“</span><p>یادگیری حرفه‌ای، مسیری پیوسته از تمرین، بازخورد و ارتباط است.</p></div></div><div class="auth-card surface">
<header><span class="eyebrow">حساب منتوریس</span><h2><?= $loginWithEmail ? 'ورود با ایمیل' : 'ورود با شمارهٔ موبایل' ?></h2><p>حساب ندارید؟ <a href="/register">رایگان عضو شوید</a></p></header>
<?php if(isset($errors['credentials'])): ?><div class="alert alert--danger" role="alert"><strong><?= e($errors['credentials'][0]) ?></strong></div><?php elseif($errors): ?><div class="alert alert--danger" role="alert"><strong>اطلاعات ورود را بررسی کنید.</strong></div><?php endif; ?>
<form class="stack" method="post" action="/login"><?= csrf_field() ?><input type="hidden" name="login_method" value="<?= $loginWithEmail ? 'email' : 'phone' ?>">
<label class="form-group"><span class="form-label"><?= $loginWithEmail ? 'ایمیل حساب' : 'شمارهٔ موبایل' ?></span><input class="form-control ltr" type="<?= $loginWithEmail ? 'email' : 'tel' ?>" name="identifier" inputmode="<?= $loginWithEmail ? 'email' : 'tel' ?>" autocomplete="username" maxlength="<?= $loginWithEmail ? 120 : 24 ?>" placeholder="<?= $loginWithEmail ? 'name@example.com' : '09123456789' ?>" value="<?= e(is_string($identifier) ? $identifier : '') ?>" aria-invalid="<?= isset($errors['identifier']) ? 'true' : 'false' ?>" required><?php if(isset($errors['identifier'])): ?><span class="form-error"><?= e($errors['identifier'][0]) ?></span><?php endif; ?></label>
<label class="form-group"><span class="form-label">رمز عبور</span><div class="password-control"><input class="form-control ltr" type="password" name="password" autocomplete="current-password" maxlength="128" required><button type="button" class="password-toggle" data-password-toggle aria-label="نمایش رمز عبور" aria-pressed="false"><?= icon('eye') ?></button></div><?php if(isset($errors['password'])): ?><span class="form-error"><?= e($errors['password'][0]) ?></span><?php endif; ?></label>
<div class="auth-form-row"><a href="<?= $loginWithEmail ? '/login' : '/login?method=email' ?>"><?= $loginWithEmail ? 'ورود با شمارهٔ موبایل' : 'ورود با ایمیل' ?></a><a href="/forgot-password">رمز عبور را فراموش کرده‌اید؟</a></div><button class="btn btn--primary btn--lg w-full" type="submit">ورود به حساب <?= icon('arrow-left') ?></button></form>
</div></div></section>
