<section class="auth-page auth-page--simple"><div class="container auth-grid">
<div class="auth-intro stack"><span class="eyebrow">خوش آمدید به منتوریس</span><h1>شروع یک مسیر<br>با هم، حرفه‌ای‌تر.</h1><p>یک حساب برای یادگیری، نشست‌ها و جامعهٔ حرفه‌ای. اطلاعات تخصصی را بعداً، در زمان مناسب، کامل کنید.</p><div class="auth-benefits"><span><?= icon('user') ?> حساب رایگان</span><span><?= icon('file') ?> ابزارهای کاربردی</span><span><?= icon('users') ?> ارتباط حرفه‌ای</span></div></div>
<div class="auth-card surface"><header><h2>ساخت حساب</h2><p>قبلاً عضو شده‌اید؟ <a href="/login">وارد شوید</a></p></header>
<?php if($errors):?><div class="alert alert--danger" role="alert"><strong>این موارد را اصلاح کنید:</strong><ul><?php foreach($errors as $messages):?><li><?= e($messages[0]) ?></li><?php endforeach;?></ul></div><?php endif;?>
<form class="stack" method="post" action="/register" data-quick-register><?= csrf_field() ?>
<?php foreach(['name'=>['نام و نام خانوادگی','text','name'],'phone'=>['شماره موبایل','tel','tel'],'email'=>['ایمیل','email','email']] as $key=>$config):?><label class="form-group"><span class="form-label"><?= e($config[0]) ?> *</span><input class="form-control <?= $key==='name' ? '' : 'ltr' ?>" type="<?= $config[1] ?>" name="<?= $key ?>" autocomplete="<?= $config[2] ?>" maxlength="<?= $key==='phone' ? 20 : 120 ?>" value="<?= e(is_string($old[$key] ?? null) ? $old[$key] : '') ?>" required <?= $key==='phone' ? 'placeholder="09123456789" inputmode="tel"' : '' ?> aria-invalid="<?= isset($errors[$key]) ? 'true' : 'false' ?>"></label><?php endforeach;?>
<fieldset class="member-type-choices"><legend>نوع عضویت *</legend><?php foreach(\App\Services\MemberProfileService::OPTIONS['member_type'] as $key=>$label):?><label><input type="radio" name="member_type" value="<?= $key ?>" <?= ($old['member_type'] ?? '')===$key ? 'checked' : '' ?> required><span><?= e($label) ?></span></label><?php endforeach;?></fieldset>
<div class="grid grid--2"><?php foreach(['password'=>'رمز عبور','password_confirmation'=>'تکرار رمز'] as $key=>$label):?><label class="form-group"><span class="form-label"><?= e($label) ?> *</span><div class="password-control"><input class="form-control ltr" type="password" name="<?= $key ?>" autocomplete="new-password" minlength="8" maxlength="128" required><button type="button" class="password-toggle" data-password-toggle aria-label="نمایش <?= e($label) ?>" aria-pressed="false"><?= icon('eye') ?></button></div></label><?php endforeach;?></div><small class="form-hint">حداقل ۸ کاراکتر، شامل یک حرف انگلیسی و یک عدد.</small>
<label class="check"><input type="checkbox" name="accept" value="1" <?= ($old['accept'] ?? '')==='1' ? 'checked' : '' ?> required><span>قوانین استفاده و حریم خصوصی منتوریس را می‌پذیرم.</span></label>
<label class="check"><input type="checkbox" name="marketing_consent" value="1" <?= ($old['marketing_consent'] ?? '')==='1' ? 'checked' : '' ?>><span>مایلم خبر دوره‌ها و نشست‌ها را با ایمیل دریافت کنم. <small>(اختیاری)</small></span></label>
<button class="btn btn--primary btn--lg w-full" type="submit">ساخت حساب و ورود به پروفایل <?= icon('arrow-left') ?></button><p class="form-hint">بدون کد تأیید. تکمیل اطلاعات تخصصی مانع ساخت حساب نیست.</p>
</form></div></div></section>
