<?php use App\Core\Authorization; $maxTrend = max(1, ...array_values($trends['users'] ?: [1])); $canUsers=Authorization::can($admin,'users.view'); $canOrders=Authorization::can($admin,'orders.view'); $canEngagements=Authorization::can($admin,'engagements.view'); $canSystem=Authorization::can($admin,'system.view'); ?>
<header class="admin-page-head"><div><span class="eyebrow">Mission Control</span><h1>سلام <?= e(explode(' ', $admin['name'] ?? '')[0] ?: 'مدیر') ?>، آماده‌ای؟</h1><p>تصویر زنده عملیات منتوریس؛ از کاربران و درآمد تا درخواست‌های نیازمند رسیدگی و وضعیت امنیت.</p></div><div class="admin-head-actions"><span class="live-indicator"><i></i> داده زنده</span><span class="admin-role-badge"><?= e(Authorization::roleLabel(Authorization::role($admin))) ?></span></div></header>

<section class="admin-kpis admin-kpis--hero" aria-label="شاخص‌های کلیدی">
    <a href="<?= $canUsers?'/admin/users':'/admin' ?>"><span>کل کاربران</span><strong><?= number_format($stats['users']) ?></strong><small><b>+<?= number_format($stats['new_users_30d']) ?></b> عضو در ۳۰ روز</small></a>
    <a href="<?= $canOrders?'/admin/orders':'/admin' ?>"><span>درآمد ثبت‌شده</span><strong><?= number_format($stats['revenue']) ?></strong><small><?= number_format($stats['revenue_30d']) ?> تومان در ۳۰ روز</small></a>
    <a href="<?= $canOrders?'/admin/orders?status=paid':'/admin' ?>"><span>سفارش موفق</span><strong><?= number_format($stats['paid_orders']) ?></strong><small><?= number_format($stats['pending_orders']) ?> سفارش در انتظار</small></a>
    <a href="<?= $canEngagements?'/admin/engagements':'/admin' ?>"><span>نیازمند رسیدگی</span><strong><?= number_format($stats['event_requests'] + $stats['community_requests'] + $stats['unread_messages']) ?></strong><small>پیام، رویداد و عضویت جامعه</small></a>
</section>

<section class="admin-command-grid">
    <?php if($canUsers): ?><a href="/admin/users"><span><?= icon('users', 'ui-icon--lg') ?></span><div><strong>مدیریت کاربران</strong><small>نقش، تعلیق، پرونده و اعلان</small></div></a><?php endif; ?>
    <?php if($canOrders): ?><a href="/admin/orders"><span><?= icon('card', 'ui-icon--lg') ?></span><div><strong>امور مالی</strong><small>سفارش، تراکنش و ثبت‌نام</small></div></a><?php endif; ?>
    <?php if($canEngagements): ?><a href="/admin/engagements"><span><?= icon('message', 'ui-icon--lg') ?></span><div><strong>صندوق عملیات</strong><small>پیام‌ها و درخواست‌های جدید</small></div></a><?php endif; ?>
    <?php if($canSystem): ?><a href="/admin/system"><span><?= icon('shield', 'ui-icon--lg') ?></span><div><strong>مرکز امنیت</strong><small>نشست‌ها و سلامت سرویس‌ها</small></div></a><?php endif; ?>
</section>

<div class="admin-grid admin-grid--wide"><section class="admin-panel"><header><div><span class="eyebrow">Growth</span><h2>رشد کاربران</h2></div><a href="/admin/analytics">گزارش کامل</a></header><div class="trend-chart" role="img" aria-label="روند عضویت کاربران"><?php foreach ($trends['users'] as $period=>$count): ?><div><span style="height:<?= max(8, round($count/$maxTrend*100)) ?>%"><b><?= number_format($count) ?></b></span><small class="ltr"><?= e(substr($period, 5)) ?></small></div><?php endforeach; ?><?php if (!$trends['users']): ?><p>داده‌ای برای نمایش نیست.</p><?php endif; ?></div></section>
<section class="admin-panel admin-attention"><header><div><span class="eyebrow">Attention</span><h2>صف رسیدگی</h2></div></header><a href="/admin/engagements?type=messages&status=new"><span>پیام‌های خوانده‌نشده</span><strong><?= number_format($stats['unread_messages']) ?></strong></a><a href="/admin/engagements?type=circle&status=requested"><span>درخواست حضور حلقه</span><strong><?= number_format($stats['event_requests']) ?></strong></a><a href="/admin/engagements?type=community&status=pending"><span>عضویت جامعه</span><strong><?= number_format($stats['community_requests']) ?></strong></a><a href="/admin/system"><span>تراکنش ناموفق ۲۴ ساعت</span><strong><?= number_format($stats['failed_transactions_24h']) ?></strong></a></section></div>

<div class="admin-grid"><section class="admin-panel"><header><div><span class="eyebrow">Recent users</span><h2>کاربران تازه</h2></div><a href="/admin/users">مشاهده همه</a></header><div class="admin-user-list"><?php foreach ($recentUsers as $user): ?><a href="/admin/users/<?= e($user['id']) ?>"><span><?= e(mb_substr($user['name'],0,1)) ?></span><div><strong><?= e($user['name']) ?></strong><small class="ltr"><?= e($user['email']) ?></small></div><em><?= e(Authorization::roleLabel(Authorization::role($user))) ?></em></a><?php endforeach; ?><?php if (!$recentUsers): ?><p class="admin-empty-row">هنوز کاربری ثبت نشده است.</p><?php endif; ?></div></section>
<section class="admin-panel"><header><div><span class="eyebrow">Commerce</span><h2>سفارش‌های اخیر</h2></div><a href="/admin/orders">مشاهده همه</a></header><div class="admin-order-list"><?php foreach ($recentOrders as $order): ?><a href="/admin/orders/<?= e($order['id']) ?>"><div><strong><?= e($order['item_title']) ?></strong><small class="ltr"><?= e($order['number']) ?></small></div><span><?= number_format((int)$order['amount']) ?></span><em class="order-status order-status--<?= e($order['status']) ?>"><?= e($order['status']) ?></em></a><?php endforeach; ?><?php if (!$recentOrders): ?><p class="admin-empty-row">هنوز سفارشی ثبت نشده است.</p><?php endif; ?></div></section></div>

<section class="admin-panel admin-audit-preview"><header><div><span class="eyebrow">Audit trail</span><h2>آخرین فعالیت‌های مدیریتی</h2></div><a href="/admin/audit">مشاهده گزارش</a></header><div><?php foreach ($recentAudit as $log): ?><article><i></i><div><strong><?= e($log['action']) ?></strong><small><?= e($log['actor_name'] ?: 'سیستم') ?> · <?= e($log['subject_type']) ?></small></div><time class="ltr"><?= e(substr($log['created_at'],0,16)) ?></time></article><?php endforeach; ?><?php if (!$recentAudit): ?><p class="admin-empty-row">فعالیت مدیریتی تازه‌ای ثبت نشده است.</p><?php endif; ?></div></section>
