<?php use App\Core\Authorization; $maxTrend = max(1, ...array_values($trends['users'] ?: [1])); $canUsers=Authorization::can($admin,'users.view'); $canOrders=Authorization::can($admin,'orders.view'); $canEngagements=Authorization::can($admin,'engagements.view'); $canContent=Authorization::can($admin,'content.view'); $canManageContent=Authorization::can($admin,'content.manage'); $attentionCount=$stats['event_requests']+$stats['community_requests']+$stats['unread_messages']; $contentStatusLabels=['published'=>'منتشرشده','draft'=>'پیش‌نویس','archived'=>'بایگانی']; ?>
<header class="admin-page-head admin-welcome"><div><span class="eyebrow">MENTORIS / WORKSPACE</span><h1>سلام <?= e(explode(' ', $admin['name'] ?? '')[0] ?: 'مدیر') ?>، خوش آمدی.</h1><p>کارهای مهم امروز، وضعیت محتوا و مسیر رشد جامعه را از همین‌جا دنبال کن.</p></div><div class="admin-head-actions"><span class="live-indicator"><i></i> داده‌های به‌روز</span><span class="admin-role-badge"><?= e(Authorization::roleLabel(Authorization::role($admin))) ?></span></div></header>

<section class="admin-kpis admin-kpis--hero" aria-label="شاخص‌های کلیدی">
    <a href="<?= $canUsers?'/admin/users':'/admin' ?>"><span>کل کاربران</span><strong><?= number_format($stats['users']) ?></strong><small><b>+<?= number_format($stats['new_users_30d']) ?></b> عضو در ۳۰ روز</small></a>
    <?php if($canEngagements): ?><a href="/admin/engagements"><span>در صف رسیدگی</span><strong><?= number_format($attentionCount) ?></strong><small>پیام، درخواست حضور و عضویت</small></a><?php endif; ?>
    <?php if($canContent && $contentBrief): ?><a href="/admin/content?status=published"><span>محتوای منتشرشده</span><strong><?= number_format($contentBrief['published']) ?></strong><small>صفحه، مقاله و رویداد</small></a><a href="/admin/content?status=draft"><span>پیش‌نویس‌ها</span><strong><?= number_format($contentBrief['draft']) ?></strong><small>آمادهٔ بازبینی و انتشار</small></a><?php endif; ?>
</section>

<section class="admin-quick-actions" aria-label="دسترسی سریع"><div><span class="eyebrow">اقدام سریع</span><h2>امروز چه کاری پیش می‌بریم؟</h2></div><nav>
    <?php if($canManageContent): ?><a href="/admin/content/new?type=article"><?= icon('file') ?> نوشتن مقاله</a><a href="/admin/content/new?type=event"><?= icon('calendar') ?> ساخت رویداد</a><?php endif; ?>
    <?php if($canEngagements): ?><a href="/admin/engagements?type=circle&status=requested"><?= icon('message') ?> بررسی درخواست‌ها</a><?php endif; ?>
    <?php if($canEngagements): ?><a href="/admin/telegram"><?= icon('message') ?> پرسش‌های تلگرام</a><a href="/admin/feedback"><?= icon('chart') ?> آمار نظرسنجی</a><?php endif; ?>
    <?php if($canContent): ?><a href="/admin/qr"><?= icon('activity') ?> ساخت و چاپ QR</a><?php endif; ?>
    <?php if($canUsers): ?><a href="/admin/users"><?= icon('users') ?> مدیریت کاربران</a><?php endif; ?>
</nav></section>

<?php if($canContent && $contentBrief): ?><section class="admin-panel admin-publishing"><header><div><span class="eyebrow">Publishing desk</span><h2>میز انتشار</h2></div><a href="/admin/content">مدیریت محتوا</a></header>
    <?php if(!$contentBrief['available']): ?><p class="admin-empty-row">برای فعال‌شدن استودیوی محتوا، مایگریشن پایگاه داده را اجرا کنید.</p><?php else: ?>
    <div class="admin-publishing__grid"><div class="admin-publishing__summary"><p>وضعیت محتوای قابل مدیریت</p><div><span><strong><?= number_format($contentBrief['published']) ?></strong> منتشرشده</span><span><strong><?= number_format($contentBrief['draft']) ?></strong> پیش‌نویس</span><span><strong><?= number_format($contentBrief['needs_translation']) ?></strong> ترجمهٔ ناتمام</span></div><a class="btn btn--secondary btn--sm" href="/admin/content?status=draft">بازبینی پیش‌نویس‌ها <?= icon('arrow-left') ?></a></div><div class="admin-publishing__recent"><h3>آخرین تغییرات</h3><?php foreach($contentBrief['recent'] as $item): ?><a href="<?= $canManageContent ? '/admin/content/' . e($item['id']) . '/edit' : '/admin/content' ?>"><div><strong><?= e($item['title']) ?></strong><small class="ltr"><?= e(substr($item['updated_at'],0,16)) ?></small></div><span class="content-status content-status--<?= e($item['status']) ?>"><?= e($contentStatusLabels[$item['status']] ?? $item['status']) ?></span></a><?php endforeach; ?><?php if(!$contentBrief['recent']): ?><p>هنوز محتوای دیتابیسی ثبت نشده است.</p><?php endif; ?></div></div>
    <?php endif; ?>
</section><?php endif; ?>

<div class="admin-grid admin-grid--wide"><section class="admin-panel"><header><div><span class="eyebrow">Growth</span><h2>رشد کاربران</h2></div><?php if(Authorization::can($admin,'analytics.view')): ?><a href="/admin/analytics">گزارش کامل</a><?php endif; ?></header><div class="trend-chart" role="img" aria-label="روند عضویت کاربران"><?php foreach ($trends['users'] as $period=>$count): ?><div><span style="height:<?= max(8, round($count/$maxTrend*100)) ?>%"><b><?= number_format($count) ?></b></span><small class="ltr"><?= e(substr($period, 5)) ?></small></div><?php endforeach; ?><?php if (!$trends['users']): ?><p>داده‌ای برای نمایش نیست.</p><?php endif; ?></div></section>
<?php if($canEngagements): ?><section class="admin-panel admin-attention"><header><div><span class="eyebrow">Attention</span><h2>صف رسیدگی</h2></div><span class="admin-count"><?= number_format($attentionCount) ?> مورد</span></header><a href="/admin/engagements?type=messages&status=new"><span>پیام‌های خوانده‌نشده</span><strong><?= number_format($stats['unread_messages']) ?></strong></a><a href="/admin/engagements?type=circle&status=requested"><span>درخواست حضور حلقه</span><strong><?= number_format($stats['event_requests']) ?></strong></a><a href="/admin/engagements?type=community&status=pending"><span>عضویت جامعه</span><strong><?= number_format($stats['community_requests']) ?></strong></a></section><?php endif; ?></div>

<?php if($canUsers || ($canOrders && $recentOrders)): ?><div class="admin-grid"><?php if($canUsers): ?><section class="admin-panel"><header><div><span class="eyebrow">Recent users</span><h2>کاربران تازه</h2></div><a href="/admin/users">مشاهده همه</a></header><div class="admin-user-list"><?php foreach ($recentUsers as $user): ?><a href="/admin/users/<?= e($user['id']) ?>"><span><?= e(mb_substr($user['name'],0,1)) ?></span><div><strong><?= e($user['name']) ?></strong><small class="ltr"><?= e($user['email']) ?></small></div><em><?= e(Authorization::roleLabel(Authorization::role($user))) ?></em></a><?php endforeach; ?><?php if (!$recentUsers): ?><p class="admin-empty-row">هنوز کاربری ثبت نشده است.</p><?php endif; ?></div></section><?php endif; ?>
<?php if($canOrders && $recentOrders): ?><section class="admin-panel"><header><div><span class="eyebrow">Commerce</span><h2>سفارش‌های اخیر</h2></div><a href="/admin/orders">مشاهده همه</a></header><div class="admin-order-list"><?php foreach ($recentOrders as $order): ?><a href="/admin/orders/<?= e($order['id']) ?>"><div><strong><?= e($order['item_title']) ?></strong><small class="ltr"><?= e($order['number']) ?></small></div><span><?= number_format((int)$order['amount']) ?></span><em class="order-status order-status--<?= e($order['status']) ?>"><?= e($order['status']) ?></em></a><?php endforeach; ?></div></section><?php endif; ?></div><?php endif; ?>

<?php if(Authorization::can($admin,'audit.view')): ?><section class="admin-panel admin-audit-preview"><header><div><span class="eyebrow">Audit trail</span><h2>آخرین فعالیت‌های مدیریتی</h2></div><a href="/admin/audit">مشاهده گزارش</a></header><div><?php foreach ($recentAudit as $log): ?><article><i></i><div><strong><?= e($log['action']) ?></strong><small><?= e($log['actor_name'] ?: 'سیستم') ?> · <?= e($log['subject_type']) ?></small></div><time class="ltr"><?= e(substr($log['created_at'],0,16)) ?></time></article><?php endforeach; ?><?php if (!$recentAudit): ?><p class="admin-empty-row">فعالیت مدیریتی تازه‌ای ثبت نشده است.</p><?php endif; ?></div></section><?php endif; ?>
