<?php use App\Core\Authorization; ?>
<header class="admin-page-head"><div><span class="eyebrow">Control Center</span><h1>سلام <?= e(explode(' ', $admin['name'] ?? '')[0] ?: 'مدیر') ?>، خوش آمدید</h1><p>نمای لحظه‌ای از کاربران، محتوا و عملیات منتوریس بر اساس داده‌های واقعی سامانه.</p></div><span class="admin-role-badge"><?= e(Authorization::roleLabel(Authorization::role($admin))) ?></span></header>

<section class="admin-kpis" aria-label="شاخص‌های کلیدی">
    <a href="/admin/users"><span>کاربران</span><strong><?= number_format($stats['users']) ?></strong><small><?= number_format($stats['new_users_30d']) ?> عضو جدید در ۳۰ روز</small></a>
    <a href="/admin/content"><span>رویدادهای منتشرشده</span><strong><?= number_format($stats['events']) ?></strong><small><?= number_format($stats['courses']) ?> دوره منتشرشده</small></a>
    <a href="/admin/analytics"><span>سفارش‌های موفق</span><strong><?= number_format($stats['paid_orders']) ?></strong><small>از <?= number_format($stats['orders']) ?> سفارش</small></a>
    <a href="/admin/analytics"><span>درآمد ثبت‌شده</span><strong><?= number_format($stats['revenue']) ?></strong><small>تومان</small></a>
</section>

<div class="admin-grid"><section class="admin-panel"><header><div><span class="eyebrow">Recent users</span><h2>کاربران تازه</h2></div><a href="/admin/users">مشاهده همه</a></header><?php if ($recentUsers): ?><div class="admin-user-list"><?php foreach ($recentUsers as $user): ?><article><span><?= e(mb_substr($user['name'],0,1)) ?></span><div><strong><?= e($user['name']) ?></strong><small class="ltr"><?= e($user['email']) ?></small></div><em><?= e(Authorization::roleLabel(Authorization::role($user))) ?></em></article><?php endforeach; ?></div><?php else: ?><?php $emptyIcon='◎'; require view_path('components/content-empty.php'); ?><?php endif; ?></section>
<section class="admin-panel"><header><div><span class="eyebrow">Commerce</span><h2>سفارش‌های اخیر</h2></div><a href="/admin/analytics">گزارش کامل</a></header><?php if ($recentOrders): ?><div class="admin-order-list"><?php foreach ($recentOrders as $order): ?><article><div><strong><?= e($order['item_title']) ?></strong><small class="ltr"><?= e($order['number']) ?></small></div><span><?= number_format((int)$order['amount']) ?> تومان</span><em class="order-status order-status--<?= e($order['status']) ?>"><?= e($order['status']) ?></em></article><?php endforeach; ?></div><?php else: ?><?php $emptyTitle='هنوز سفارشی ثبت نشده'; $emptyText='پس از فعال‌شدن فروش، سفارش‌های واقعی اینجا نمایش داده می‌شوند.'; $emptyIcon='◧'; require view_path('components/content-empty.php'); ?><?php endif; ?></section></div>
