<?php use App\Core\Authorization; ?>
<header class="admin-page-head"><div><span class="eyebrow">منتوریس در جست‌وجو</span><h1>سئو و حضور در گوگل</h1><p>آمادگی محتوا را بررسی کنید و سایت را به حساب Search Console خود متصل کنید.</p></div><a class="btn btn--secondary" href="<?= e($baseUrl) ?>/sitemap.xml" target="_blank" rel="noopener">مشاهدهٔ نقشهٔ سایت <?= icon('arrow-up-left') ?></a></header>
<section class="admin-panel admin-seo-guide"><header><h2>راه‌اندازی جست‌وجوی نام «منتوریس»</h2></header><ol>
<li>در <a href="https://search.google.com/search-console" target="_blank" rel="noopener">Google Search Console</a> یک Domain property برای <code class="ltr">mentorisacademy.com</code> بسازید و TXT ارائه‌شده را به DNS دامنه اضافه کنید.</li>
<li>پس از تأیید مالکیت، در بخش Sitemaps آدرس <code class="ltr"><?= e($baseUrl) ?>/sitemap.xml</code> را ثبت کنید.</li>
<li>در URL Inspection، صفحهٔ اصلی و مقالات مهم را بررسی کنید؛ اگر لازم بود Request indexing را بزنید.</li>
<li>نام «آکادمی منتوریس» و لینک سایت را در معرفی، صفحهٔ دربارهٔ ما و پروفایل‌های رسمی یکسان نگه دارید. مقاله‌های مفید و مرتبط با فعالیت آکادمی منتشر کنید.</li>
<li>در گزارش Page indexing خطاهای مسدودشدن، صفحات تکراری و صفحات ایندکس‌نشده را دنبال کنید. ایندکس‌شدن و جایگاه جست‌وجو آنی یا تضمینی نیست.</li>
</ol><p class="form-hint">برای روش URL-prefix می‌توانید مقدار تأیید HTML را در متغیر GOOGLE_SITE_VERIFICATION هاست بگذارید. این صفحه به حساب گوگل وصل نیست؛ وضعیت واقعی ایندکس را در Search Console ببینید.</p></section>
<section class="admin-panel mt-8"><header><div><h2>بازبینی مقاله‌های منتشرشده</h2><p>آخرین ۱۰۰ مقالهٔ دیتابیسی؛ این بررسی محتوایی، رتبه یا ایندکس گوگل را اندازه‌گیری نمی‌کند.</p></div><span><?= number_format($articleTotal) ?> مقاله</span></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>مقاله</th><th>موارد قابل تکمیل</th><th></th></tr></thead><tbody><?php foreach($reviews as $review): ?><tr><td><?= e($review['entry']['translations']['fa']['title'] ?? $review['entry']['slug']) ?></td><td><?= e($review['issues'] ? implode(' · ',$review['issues']) : 'متن، خلاصه و تصویر ثبت شده‌اند.') ?></td><td><?php if(Authorization::can($admin,'content.manage')): ?><a class="table-action" href="/admin/articles/<?= e($review['entry']['id']) ?>/edit">تکمیل مقاله</a><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$reviews): ?><tr><td colspan="3">هنوز مقالهٔ منتشرشده‌ای در دیتابیس نیست.</td></tr><?php endif; ?></tbody></table></div></section>
