<?php $canManage=\App\Core\Authorization::can($admin,'engagements.manage'); ?>
<header class="admin-page-head"><div><span class="eyebrow">ارتباط نزدیک‌تر</span><h1>همراه تلگرامی منتوریس</h1><p>پرسش‌ها و درخواست‌های شرکت در نشست‌ها؛ آخرین ۱۰۰ مورد هر بخش.</p></div><a class="btn btn--secondary" href="https://t.me/mentorisacademy_bot" target="_blank" rel="noopener">بازکردن ربات</a></header>
<?php if($notice):?><div class="alert alert--success" role="status"><?= e($notice) ?></div><?php endif;?>
<?php if(!$report['ready'] || !$configured):?><div class="alert alert--danger">برای فعال‌شدن ربات، SQL شمارهٔ ۰۰۵، تنظیمات خصوصی تلگرام، وب‌هوک و Cron هاست را طبق راهنمای نصب تکمیل کنید. <?= $report['ready'] ? 'جدول‌ها آماده‌اند.' : 'جدول‌ها هنوز آماده نیستند.' ?> <?= $configured ? 'توکن تنظیم شده است.' : 'توکن تنظیم نشده است.' ?></div><?php endif;?>
<section class="admin-kpis"><?php foreach(['users'=>'کاربر تلگرام','questions'=>'پرسش','requests'=>'درخواست نشست','pending'=>'پرسش بی‌پاسخ','failed'=>'کار ناموفق'] as $key=>$label):?><div><span><?= $label ?></span><strong><?= number_format($report['stats'][$key]) ?></strong></div><?php endforeach;?></section>
<p>پاسخ‌ها با اجرای Cron ارسال می‌شوند. آمار «پاسخ داده‌شده» به معنی ثبت پاسخ در صف است. پیام‌های ناموفق پس از رفع مشکل قابل تلاش مجدد هستند.</p>
<?php if($canManage && $report['stats']['failed']):?><form method="post" action="/admin/telegram/retry"><?= csrf_field() ?><button class="btn btn--secondary">تلاش مجدد ارسال‌های ناموفق</button></form><?php endif;?>
<form method="get" class="member-filters"><label><span>جست‌وجو در نام یا سؤال</span><input class="form-control" name="q" value="<?= e(is_string($filters['q'] ?? null) ? $filters['q'] : '') ?>"></label><label><span>وضعیت</span><select name="status" class="form-select"><option value="">همه</option><?php foreach(['new'=>'بی‌پاسخ','answered'=>'پاسخ ثبت‌شده'] as $key=>$label):?><option value="<?= $key ?>" <?= ($filters['status'] ?? '')===$key ? 'selected' : '' ?>><?= $label ?></option><?php endforeach;?></select></label><button class="btn btn--primary">اعمال فیلتر</button></form>
<section class="stack"><?php foreach($report['questions'] as $question):?><article class="admin-panel"><header><h2><?= e($question['display_name']) ?></h2><small><bdi><?= e($question['username'] ? '@'.$question['username'] : 'بدون نام کاربری') ?></bdi> · <?= e($question['created_at']) ?></small></header><p><?= nl2br(e($question['question'])) ?></p><?php if($question['status']==='answered'):?><div class="alert alert--success"><strong>پاسخ ثبت‌شده</strong><p><?= nl2br(e($question['answer'])) ?></p></div><?php elseif($canManage):?><form class="stack" method="post" action="/admin/telegram/questions/<?= e($question['id']) ?>/answer"><?= csrf_field() ?><label><span class="form-label">پاسخ تیم</span><textarea class="form-control" name="answer" rows="3" minlength="3" maxlength="3000" required></textarea></label><button class="btn btn--primary">ثبت و ارسال پاسخ</button></form><?php endif;?></article><?php endforeach;?><?php if(!$report['questions']):?><p class="alert">پرسشی مطابق فیلتر پیدا نشد.</p><?php endif;?></section>
<h2>درخواست شرکت در نشست</h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>نام / تماس</th><th>نشست</th><th>شهر</th><th>وضعیت</th><th>تاریخ</th></tr></thead><tbody><?php foreach($report['requests'] as $row):?><tr><td><?= e($row['name']) ?><small><a href="tel:<?= e($row['phone']) ?>"><bdi><?= e($row['phone']) ?></bdi></a></small></td><td><?= e($row['event_slug']) ?></td><td><?= e($row['city']) ?></td><td><?php if($canManage):?><form method="post" action="/admin/telegram/requests/<?= e($row['id']) ?>"><?= csrf_field() ?><select name="status" class="form-select" aria-label="وضعیت درخواست"><?php foreach(['requested'=>'جدید','contacted'=>'تماس گرفته‌شده','confirmed'=>'تأییدشده','cancelled'=>'لغوشده'] as $key=>$label):?><option value="<?= $key ?>" <?= $row['status']===$key ? 'selected' : '' ?>><?= $label ?></option><?php endforeach;?></select><button class="btn btn--ghost btn--sm">ذخیره</button></form><?php else:?><?= e($row['status']) ?><?php endif;?></td><td><?= e($row['created_at']) ?></td></tr><?php endforeach;?><?php if(!$report['requests']):?><tr><td colspan="5">درخواستی ثبت نشده؛ ثبت‌نام دو نشست گذشته بسته است.</td></tr><?php endif;?></tbody></table></div>
