<?php use App\Core\Authorization; $options=\App\Services\MemberProfileService::OPTIONS; ?>
<header class="admin-page-head"><div><span class="eyebrow">Members & Profiles</span><h1>اعضا و پروفایل‌ها</h1><p>پروندهٔ تحصیلی، حرفه‌ای و سوابق آموزش اعضا را بررسی و ویرایش کنید.</p></div><?php if(Authorization::can($admin,'users.manage')):?><a class="btn btn--primary" href="/admin/users/new">افزودن کاربر</a><?php endif;?></header>
<section class="admin-kpis"><?php foreach(['total'=>'کل کاربران','student'=>'دانشجو','therapist'=>'درمانگر','completed'=>'پروفایل تکمیل‌شده','consented'=>'رضایت دریافت ایمیل'] as $key=>$label):?><div><span><?= e($label) ?></span><strong><?= number_format($result['stats'][$key]) ?></strong></div><?php endforeach;?></section>
<?php if(!$result['enabled']):?><div class="alert alert--danger">پروفایل‌ها فعلاً در فضای خصوصی ذخیره می‌شوند؛ برای انتقال خودکار به دیتابیس، فایل SQL به‌روزرسانی را اجرا کنید.</div><?php endif;?>
<form class="member-filters" method="get" action="/admin/users">
<label><span>نام، ایمیل یا موبایل</span><input class="form-control" type="search" name="q" value="<?= e($filters['q'] ?? '') ?>"></label>
<?php foreach(['member_type'=>'نوع عضو','degree'=>'مقطع تحصیلی','practice_status'=>'وضعیت فعالیت حرفه‌ای'] as $key=>$label):?><label><span><?= e($label) ?></span><select class="form-select" name="<?= e($key) ?>"><option value="">همه</option><?php foreach($options[$key] as $v=>$text):?><option value="<?= e($v) ?>" <?= ($filters[$key] ?? '')===$v ? 'selected' : '' ?>><?= e($text) ?></option><?php endforeach;?></select></label><?php endforeach;?>
<?php foreach(['field_of_study'=>'رشته','university'=>'دانشگاه','city'=>'شهر','specialty_fields'=>'حوزهٔ تخصصی'] as $key=>$label):?><label><span><?= e($label) ?></span><input class="form-control" name="<?= e($key) ?>" value="<?= e($filters[$key] ?? '') ?>" maxlength="160"></label><?php endforeach;?>
<label><span>نقش دسترسی</span><select class="form-select" name="account_role"><option value="">همه</option><?php foreach($roles as $v=>$text):?><option value="<?= e($v) ?>" <?= ($filters['account_role'] ?? '')===$v ? 'selected' : '' ?>><?= e($text) ?></option><?php endforeach;?></select></label>
<label><span>وضعیت حساب</span><select class="form-select" name="status"><option value="">همه</option><option value="active" <?= ($filters['status'] ?? '')==='active' ? 'selected' : '' ?>>فعال</option><option value="suspended" <?= ($filters['status'] ?? '')==='suspended' ? 'selected' : '' ?>>تعلیق‌شده</option></select></label>
<button class="btn btn--primary" type="submit">اعمال فیلتر</button><a class="btn btn--ghost" href="/admin/users">پاک‌کردن فیلترها</a>
</form><p><?= number_format($result['total']) ?> نتیجه · ۵۰ کاربر در هر صفحه</p>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>کاربر</th><th>نوع عضو / نقش دسترسی</th><th>تحصیلات</th><th>فعالیت حرفه‌ای</th><th>تکمیل پروفایل</th><th></th></tr></thead><tbody>
<?php foreach($users as $user):?><tr><td><a class="table-user" href="/admin/users/<?= e($user['id']) ?>"><span><?= e(mb_substr($user['name'],0,1)) ?></span><div><strong><?= e($user['name']) ?></strong><small class="ltr"><?= e($user['email']) ?></small><small class="ltr"><?= e($user['phone']) ?></small></div></a></td><td><?= e($options['member_type'][$user['member_type'] ?? ''] ?? 'ثبت نشده') ?><small><?= e(Authorization::roleLabel($user['account_role'])) ?> · <?= $user['status']==='active' ? 'فعال' : 'تعلیق‌شده' ?></small></td><td><?= e($user['field_of_study'] ?? '—') ?><small><?= e($options['degree'][$user['degree'] ?? ''] ?? '') ?> · <?= e($user['university'] ?? '') ?></small></td><td><?= e($user['city'] ?? '—') ?><small><?= e($options['practice_status'][$user['practice_status'] ?? ''] ?? '') ?></small><small><?= e($user['specialty_fields'] ?? '') ?></small></td><td><?= !empty($user['completed_at']) ? 'تکمیل‌شده' : 'در حال تکمیل' ?></td><td><a class="table-action" href="/admin/users/<?= e($user['id']) ?>">پروندهٔ کامل ←</a></td></tr><?php endforeach;?>
<?php if(!$users):?><tr><td colspan="6">کاربری با این فیلترها پیدا نشد.</td></tr><?php endif;?></tbody></table></div>
<nav class="member-pagination" aria-label="صفحه‌های کاربران"><?php if($result['page']>1):?><a class="btn btn--ghost" href="?<?= e(http_build_query(array_replace($filters,['page'=>$result['page']-1]))) ?>">قبلی</a><?php endif;?><span>صفحه <?= $result['page'] ?> از <?= $result['pages'] ?></span><?php if($result['page']<$result['pages']):?><a class="btn btn--ghost" href="?<?= e(http_build_query(array_replace($filters,['page'=>$result['page']+1]))) ?>">بعدی</a><?php endif;?></nav>
