<?php
$copy = [
    'fa'=>['eyebrow'=>'داستان و ماموریت','principles'=>'آنچه برای ما مهم است','p1'=>'دانش علمی','p1t'=>'محتوا و تصمیم‌های آموزشی باید بر شواهد معتبر و تفکر نقادانه استوار باشند.','p2'=>'رشد مستمر','p2t'=>'رشد حرفه‌ای یک رویداد کوتاه نیست؛ مسیری پیوسته از یادگیری، تمرین و بازخورد است.','p3'=>'ارتباط انسانی','p3t'=>'جامعه حرفه‌ای امن و محترمانه، کیفیت یادگیری و کار حرفه‌ای را عمیق‌تر می‌کند.','pathways'=>'حوزه‌های فعالیت','contact'=>'با منتوریس در ارتباط باشید'],
    'ar'=>['eyebrow'=>'القصة والرسالة','principles'=>'ما نؤمن به','p1'=>'المعرفة العلمية','p1t'=>'يجب أن يستند المحتوى والقرار التعليمي إلى الدليل الموثوق والتفكير النقدي.','p2'=>'النمو المستمر','p2t'=>'النمو المهني ليس حدثاً قصيراً، بل مسار من التعلّم والممارسة والتغذية الراجعة.','p3'=>'التواصل الإنساني','p3t'=>'المجتمع المهني الآمن والمحترم يعمّق جودة التعلّم والممارسة.','pathways'=>'مجالات العمل','contact'=>'تواصل مع منتوريس'],
    'ku'=>['eyebrow'=>'چیرۆک و ئەرک','principles'=>'ئەوەی بۆمان گرنگە','p1'=>'زانستی','p1t'=>'ناوەڕۆک و بڕیاری فێرکاری دەبێت لەسەر بەڵگەی باوەڕپێکراو و بیرکردنەوەی ڕەخنەیی بێت.','p2'=>'گەشەی بەردەوام','p2t'=>'گەشەی پیشەیی ڕووداوێکی کورت نییە؛ ڕێگایەکی فێربوون و ڕاهێنان و فیدباکە.','p3'=>'پەیوەندی مرۆیی','p3t'=>'کۆمەڵگەی پیشەیی ئارام و ڕێزدار کوالێتی فێربوون قووڵتر دەکات.','pathways'=>'بوارەکانی کار','contact'=>'پەیوەندی لەگەڵ مێنتۆریس'],
    'en'=>['eyebrow'=>'Story & mission','principles'=>'What matters to us','p1'=>'Scientific integrity','p1t'=>'Content and educational decisions should be grounded in credible evidence and critical thinking.','p2'=>'Continuous growth','p2t'=>'Professional growth is not a one-off event; it is an ongoing cycle of learning, practice, and feedback.','p3'=>'Human connection','p3t'=>'A safe and respectful professional community makes learning and practice deeper.','pathways'=>'Areas of work','contact'=>'Connect with Mentoris'],
][locale()];
?>
<section class="page-hero about-hero"><div class="container page-hero__content"><span class="eyebrow"><?= e($copy['eyebrow']) ?></span><h1><?= e($about['title']) ?></h1><p><?= e($about['lead']) ?></p></div></section>

<section class="section"><div class="container about-story-layout">
    <article class="about-manifesto stack" data-reveal><?php foreach ($about['paragraphs'] as $index => $paragraph): ?><p class="<?= $index === 0 ? 'lead-copy' : '' ?>"><?= e($paragraph) ?></p><?php endforeach; ?><blockquote><?= e($about['signature']) ?></blockquote></article>
    <aside class="about-founder-card" data-reveal><img src="<?= asset($founder['image']) ?>" alt="<?= e($founder['name']) ?>" width="1024" height="1536"><div><strong><?= e($founder['name']) ?></strong><span><?= e($founder['role']) ?></span><a href="/founder"><?= e(t('nav.founder')) ?> ←</a></div></aside>
</div></section>

<section class="section section--muted"><div class="container"><header class="section__head"><div><span class="eyebrow">Our principles</span><h2><?= e($copy['principles']) ?></h2></div></header><div class="grid grid--3"><article class="feature-card surface"><div class="feature-card__icon" aria-hidden="true">⌁</div><h3><?= e($copy['p1']) ?></h3><p><?= e($copy['p1t']) ?></p></article><article class="feature-card surface"><div class="feature-card__icon" aria-hidden="true">↗</div><h3><?= e($copy['p2']) ?></h3><p><?= e($copy['p2t']) ?></p></article><article class="feature-card surface"><div class="feature-card__icon" aria-hidden="true">◎</div><h3><?= e($copy['p3']) ?></h3><p><?= e($copy['p3t']) ?></p></article></div></div></section>

<section class="section" id="lines"><div class="container"><header class="section__head"><div><span class="eyebrow">Academy Lines</span><h2><?= e($copy['pathways']) ?></h2></div></header><div class="academy-lines-grid"><?php foreach ($lines as $index => $line): ?><a class="line-card" href="/academy/<?= e($line['slug']) ?>"><span class="line-card__number"><?= str_pad((string)($index+1),2,'0',STR_PAD_LEFT) ?></span><div class="line-card__icon" aria-hidden="true"><?= e($line['icon']) ?></div><h3><?= e($line['title']) ?></h3><span class="line-card__en"><?= e($line['en']) ?></span><p><?= e($line['description']) ?></p></a><?php endforeach; ?></div></div></section>

<section class="section section--muted"><div class="container"><div class="public-cta"><span class="eyebrow">Mentoris</span><h2><?= e($copy['contact']) ?></h2><p><?= e(t('footer.tagline')) ?></p><a class="btn btn--primary btn--lg" href="/contact"><?= e(t('nav.contact')) ?></a></div></div></section>
