<section class="page-hero"><div class="container page-hero__content" data-reveal><span class="eyebrow">About Mentoris</span><h1>برای رشد، یادگیری و <span class="text-gradient">اثرگذاری پایدار</span></h1><p>Mentoris یک آکادمی صرف نیست؛ اکوسیستمی است که آموزش معتبر، تجربه حرفه‌ای و جامعه انسانی را کنار هم قرار می‌دهد.</p></div></section>

<section class="section"><div class="container story-grid"><div class="stack" data-reveal><span class="eyebrow">Our Story</span><h2>از یک پرسش ساده شروع شد</h2><p>چطور می‌توان فاصله میان دانش دانشگاهی و تجربه واقعی حرفه‌ای را کمتر کرد؟ Mentoris با همین پرسش شکل گرفت؛ فضایی که در آن آموزش از مسئله‌های واقعی شروع می‌شود، با پژوهش معتبر عمق می‌گیرد و در جامعه حرفه‌ای ادامه پیدا می‌کند.</p><p>ما به یادگیری به‌عنوان یک رویداد کوتاه نگاه نمی‌کنیم. رشد حرفه‌ای مسیری پیوسته است و به گفتگو، تمرین، بازخورد و ارتباط نیاز دارد.</p></div><div class="story-visual" data-reveal><span>علم</span><span>تجربه</span><span>جامعه</span><div>Mentoris</div></div></div></section>

<section class="section section--muted"><div class="container"><div class="grid grid--2 mission-grid"><article class="mission-card" data-reveal><span class="eyebrow">Mission</span><h2>مأموریت</h2><p>خلق تجربه‌های یادگیری مبتنی بر شواهد، کاربردی و اخلاق‌مدار برای متخصصان و علاقه‌مندان حوزه سلامت روان.</p></article><article class="mission-card mission-card--accent" data-reveal><span class="eyebrow">Vision</span><h2>چشم‌انداز</h2><p>مرجع فارسی‌زبان توسعه حرفه‌ای و یادگیری میان‌رشته‌ای در روان‌شناسی و سلامت روان.</p></article></div><div class="stats-strip" data-reveal><div><strong>۶</strong><span>لاین تخصصی</span></div><div><strong>۳۵+</strong><span>برنامه آموزشی</span></div><div><strong>۲۰+</strong><span>استاد و پژوهشگر</span></div><div><strong>۲۸۰۰+</strong><span>عضو جامعه</span></div></div></div></section>

<section class="section"><div class="container"><header class="section__head" data-reveal><div><span class="eyebrow">Our Values</span><h2>ارزش‌هایی که تصمیم‌های ما را می‌سازند</h2></div></header><div class="grid grid--4"><article class="value-card" data-reveal><span>01</span><h3>اعتبار علمی</h3><p>تکیه بر شواهد و تفکر نقادانه.</p></article><article class="value-card" data-reveal><span>02</span><h3>انسان‌محوری</h3><p>احترام به تجربه و تفاوت‌های انسانی.</p></article><article class="value-card" data-reveal><span>03</span><h3>کاربردپذیری</h3><p>دانشی که بتوان آن را به عمل تبدیل کرد.</p></article><article class="value-card" data-reveal><span>04</span><h3>یادگیری جمعی</h3><p>رشد از مسیر گفتگو و همکاری.</p></article></div></div></section>

<section class="section section--muted" id="lines"><div class="container"><header class="section__head" data-reveal><div><span class="eyebrow">Academy Lines</span><h2>حوزه‌های فعالیت Mentoris</h2></div></header><div class="academy-lines-grid"><?php foreach ($lines as $index => $line): ?><article class="line-card" data-reveal><span class="line-card__number">0<?= $index + 1 ?></span><h3><?= e($line['title']) ?></h3><span class="line-card__en"><?= e($line['en']) ?></span><p><?= e($line['description']) ?></p></article><?php endforeach; ?></div></div></section>

<section class="section"><div class="container"><div class="public-cta"><h2>آینده یادگیری را با هم می‌سازیم</h2><p>اگر در این مسیر با ما هم‌فکر هستید، مشتاق شنیدن صدای شما هستیم.</p><div class="cluster"><a class="btn btn--primary" href="/contact">ارتباط با ما</a><a class="btn btn--ghost" href="/programs">برنامه‌های آموزشی</a></div></div></div></section>
