<section class="community-landing"><div class="container community-landing__grid"><div class="stack" data-reveal><span class="eyebrow">Mentoris Community</span><h1>جایی برای <span class="text-gradient">یادگیری و تعلق حرفه‌ای</span></h1><p>جامعه‌ای امن و حرفه‌ای برای متخصصان، دانشجویان و پژوهشگرانی که می‌خواهند کنار هم یاد بگیرند، گفتگو کنند و رشد کنند.</p><div class="cluster"><a class="btn btn--primary btn--lg" href="#join">درخواست عضویت</a><a class="btn btn--ghost btn--lg" href="#rules">قوانین Community</a></div><div class="community-member-proof"><strong><?= e($community['member_count']) ?></strong><span>عضو هم‌مسیر در اکوسیستم Mentoris</span></div></div><div class="community-network" aria-hidden="true"><span class="community-network__core">M</span><i>گفتگو</i><i>یادگیری</i><i>همکاری</i><i>رویداد</i></div></div></section>

<section class="section" id="benefits"><div class="container"><header class="section__head"><div><span class="eyebrow">Membership Benefits</span><h2>عضویت چه تجربه‌ای می‌سازد؟</h2><p>نسخه اول Community روی ارتباط معنادار، منابع منتخب و رویدادهای کوچک تمرکز دارد.</p></div></header><div class="grid grid--4 community-benefits"><?php foreach ($community['benefits'] as $benefit): ?><article class="community-benefit" data-reveal><span><?= e($benefit['icon']) ?></span><h3><?= e($benefit['title']) ?></h3><p><?= e($benefit['description']) ?></p></article><?php endforeach; ?></div></div></section>

<section class="section section--muted" id="rules"><div class="container community-rules"><div class="stack" data-reveal><span class="eyebrow">Community Rules</span><h2>فضایی امن، محترمانه و حرفه‌ای</h2><p>حضور در Community یعنی پذیرفتن چند اصل ساده که کیفیت و امنیت گفتگو را برای همه حفظ می‌کند.</p><div class="community-scope"><strong>محدوده نسخه MVP</strong><p>در این نسخه، Community یک شبکه اجتماعی کامل نیست؛ عضویت، رویدادها، قوانین و ارتباط با تیم را فراهم می‌کنیم.</p></div></div><ol class="community-rules__list" data-reveal><?php foreach ($community['rules'] as $index => $rule): ?><li><span>0<?= $index + 1 ?></span><p><?= e($rule) ?></p></li><?php endforeach; ?></ol></div></section>

<section class="section" id="community-events"><div class="container"><header class="section__head"><div><span class="eyebrow">Community Events</span><h2>رویدادهای پیش‌روی اعضا</h2><p>از نشست‌های آزاد تا حلقه‌های کوچک تمرین و سوپرویژن.</p></div><a class="btn btn--ghost btn--sm" href="/events">همه رویدادها</a></header><div class="grid grid--3"><?php foreach ($events as $event): require view_path('components/cards/event-card.php'); endforeach; ?></div></div></section>

<section class="section section--muted" id="join"><div class="container community-join"><div class="community-join__intro stack" data-reveal><span class="eyebrow">Join Mentoris</span><h2>به Community بپیوندید</h2><p>فرم کوتاه روبه‌رو را پر کنید. تیم Community درخواست شما را بررسی می‌کند و اطلاعات مرحله بعد را برایتان می‌فرستد.</p><ul class="check-list"><li>عضویت پایه رایگان</li><li>بدون نیاز به سابقه عضویت قبلی</li><li>امکان لغو عضویت در هر زمان</li></ul></div><div class="community-join__form surface" data-reveal>
    <?php if ($success): ?><div class="alert alert--success" role="status"><strong>درخواست عضویت شما ثبت شد.</strong><p>خوشحالیم که به جمع منتوریس نزدیک‌تر شدید.</p></div><?php endif; ?>
    <?php if ($errors): ?><div class="alert alert--danger" role="alert"><strong>لطفاً موارد مشخص‌شده را اصلاح کنید.</strong></div><?php endif; ?>
    <?php if (!$success): ?><form class="stack" method="post" action="/community/join"><?= csrf_field() ?><div class="grid grid--2"><label class="form-group"><span class="form-label">نام و نام خانوادگی *</span><input class="form-control" name="name" value="<?= e($old['name'] ?? '') ?>" required><?php if (isset($errors['name'])): ?><span class="form-error"><?= e($errors['name'][0]) ?></span><?php endif; ?></label><label class="form-group"><span class="form-label">ایمیل *</span><input class="form-control ltr" type="email" name="email" value="<?= e($old['email'] ?? '') ?>" required><?php if (isset($errors['email'])): ?><span class="form-error"><?= e($errors['email'][0]) ?></span><?php endif; ?></label></div><label class="form-group"><span class="form-label">نقش حرفه‌ای *</span><select class="form-select" name="role" required><option value="">انتخاب کنید</option><?php foreach (['دانشجو','روان‌شناس / درمانگر','پژوهشگر','مدرس / منتور','فعال حوزه سلامت','سایر'] as $role): ?><option <?= ($old['role'] ?? '') === $role ? 'selected' : '' ?>><?= e($role) ?></option><?php endforeach; ?></select><?php if (isset($errors['role'])): ?><span class="form-error"><?= e($errors['role'][0]) ?></span><?php endif; ?></label><label class="form-group"><span class="form-label">حوزه‌های مورد علاقه</span><textarea class="form-textarea" name="interests" maxlength="500" placeholder="مثلاً درمان، پژوهش یا توسعه حرفه‌ای"><?= e($old['interests'] ?? '') ?></textarea></label><label class="check"><input type="checkbox" name="accept" value="1" <?= isset($old['accept']) ? 'checked' : '' ?> required><span>قوانین Community و اصل محرمانگی را می‌پذیرم.</span></label><?php if (isset($errors['accept'])): ?><span class="form-error"><?= e($errors['accept'][0]) ?></span><?php endif; ?><button class="btn btn--primary btn--lg w-full" type="submit">ارسال درخواست عضویت</button><small class="event-form-note">اطلاعات شما فقط برای هماهنگی عضویت استفاده می‌شود.</small></form><?php endif; ?>
</div></div></section>
