<?php $copy=['fa'=>['title'=>'با منتوریس در ارتباط باشید','lead'=>'برای اطلاع از رویدادها، دوره‌های آموزشی و فعالیت‌های آکادمی از راه‌های زیر با ما در تماس باشید.','email'=>'ایمیل','phone'=>'واتس‌اپ و تماس','instagram'=>'اینستاگرام','website'=>'وب‌سایت','form'=>'فرم ارتباط آنلاین'],'ar'=>['title'=>'تواصلوا مع منتوريس','lead'=>'للاطلاع على الفعاليات والدورات وأنشطة الأكاديمية، تواصلوا معنا عبر القنوات التالية.','email'=>'البريد الإلكتروني','phone'=>'واتساب والهاتف','instagram'=>'إنستغرام','website'=>'الموقع','form'=>'نموذج التواصل'],'ku'=>['title'=>'پەیوەندی لەگەڵ مێنتۆریس','lead'=>'بۆ زانیاریی بۆنەکان و کۆرسەکان و چالاکییەکانی ئەکادیمی لەم ڕێگایانەوە پەیوەندیمان پێوە بکەن.','email'=>'ئیمەیڵ','phone'=>'واتساپ و تەلەفۆن','instagram'=>'ئینستاگرام','website'=>'وێبسایت','form'=>'فۆڕمی پەیوەندی'],'en'=>['title'=>'Contact Mentoris','lead'=>'For updates about events, courses, and academy activities, reach us through the channels below.','email'=>'Email','phone'=>'WhatsApp & phone','instagram'=>'Instagram','website'=>'Website','form'=>'Online contact form']][locale()]; ?>
<section class="page-hero page-hero--compact"><div class="container page-hero__content"><span class="eyebrow">Contact Mentoris</span><h1><?= e($copy['title']) ?></h1><p><?= e($copy['lead']) ?></p></div></section>
<section class="section"><div class="container"><div class="contact-methods-grid">
    <a class="contact-method surface" href="mailto:Academichaghani@gmail.com"><span aria-hidden="true">✉</span><div><strong><?= e($copy['email']) ?></strong><p class="ltr">Academichaghani@gmail.com</p></div></a>
    <a class="contact-method surface" href="https://wa.me/989100077611" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">◉</span><div><strong><?= e($copy['phone']) ?></strong><p class="ltr">09100077611</p></div></a>
    <a class="contact-method surface" href="https://instagram.com/Mentoris_Academy" target="_blank" rel="noopener noreferrer"><span aria-hidden="true">◎</span><div><strong><?= e($copy['instagram']) ?></strong><p class="ltr">@Mentoris_Academy</p></div></a>
    <a class="contact-method surface" href="https://Mentorisacademy.com"><span aria-hidden="true">⌂</span><div><strong><?= e($copy['website']) ?></strong><p class="ltr">Mentorisacademy.com</p></div></a>
</div></div></section>
<section class="section section--muted"><div class="container container--md"><header class="section__head"><div><span class="eyebrow">Contact form</span><h2><?= e($copy['form']) ?></h2></div></header><?php $emptyIcon='✉'; require view_path('components/content-empty.php'); ?></div></section>
