<section class="page-hero page-hero--compact"><div class="container page-hero__content"><span class="eyebrow">Contact Us</span><h1>با Mentoris در <span class="text-gradient">ارتباط باشید</span></h1><p>پرسش آموزشی، پیشنهاد همکاری یا نیاز به راهنمایی دارید؟ پیام شما را با دقت می‌خوانیم.</p></div></section>

<section class="section"><div class="container contact-grid"><aside class="contact-sidebar stack" data-reveal><div><span class="eyebrow">راه‌های ارتباطی</span><h2>بیایید گفتگو کنیم</h2></div><p>تیم Mentoris معمولاً طی یک تا دو روز کاری پاسخ می‌دهد.</p><div class="contact-method"><span>✉</span><div><strong>ایمیل</strong><a class="ltr" href="mailto:info@mentoris.academy">info@mentoris.academy</a></div></div><div class="contact-method"><span>⌖</span><div><strong>نشانی</strong><p>تهران، ایران</p></div></div><div class="contact-method"><span>◷</span><div><strong>ساعات پاسخ‌گویی</strong><p>شنبه تا چهارشنبه · ۹ تا ۱۷</p></div></div><div class="contact-note"><strong>همکاری علمی و تدریس</strong><p>در موضوع پیام، گزینه همکاری حرفه‌ای را انتخاب کنید.</p></div></aside>

    <div class="surface contact-form-card" data-reveal>
        <?php if ($success): ?><div class="alert alert--success" role="status"><strong>پیام شما ثبت شد.</strong><p>از ارتباط شما متشکریم؛ تیم Mentoris به‌زودی پاسخ می‌دهد.</p></div><?php endif; ?>
        <?php if ($errors): ?><div class="alert alert--danger" role="alert"><strong>لطفاً موارد مشخص‌شده را اصلاح کنید.</strong></div><?php endif; ?>
        <form class="contact-form flow" action="/contact" method="post" novalidate>
            <?= csrf_field() ?>
            <div class="grid grid--2"><label class="form-group"><span class="form-label">نام و نام خانوادگی *</span><input class="form-control" name="name" value="<?= e($old['name'] ?? '') ?>" required aria-invalid="<?= isset($errors['name']) ? 'true' : 'false' ?>"><?php if (isset($errors['name'])): ?><span class="form-error"><?= e($errors['name'][0]) ?></span><?php endif; ?></label><label class="form-group"><span class="form-label">ایمیل *</span><input class="form-control ltr" type="email" name="email" value="<?= e($old['email'] ?? '') ?>" required aria-invalid="<?= isset($errors['email']) ? 'true' : 'false' ?>"><?php if (isset($errors['email'])): ?><span class="form-error"><?= e($errors['email'][0]) ?></span><?php endif; ?></label></div>
            <div class="grid grid--2"><label class="form-group"><span class="form-label">شماره تماس</span><input class="form-control ltr" name="phone" value="<?= e($old['phone'] ?? '') ?>" placeholder="09xxxxxxxxx"></label><label class="form-group"><span class="form-label">موضوع *</span><select class="form-select" name="subject" required><option value="">انتخاب کنید</option><?php foreach (['راهنمایی دوره‌ها','همکاری حرفه‌ای','پیشنهاد تدریس','پشتیبانی','سایر'] as $subject): ?><option <?= ($old['subject'] ?? '') === $subject ? 'selected' : '' ?>><?= e($subject) ?></option><?php endforeach; ?></select><?php if (isset($errors['subject'])): ?><span class="form-error"><?= e($errors['subject'][0]) ?></span><?php endif; ?></label></div>
            <label class="form-group"><span class="form-label">پیام شما *</span><textarea class="form-textarea" name="message" required aria-invalid="<?= isset($errors['message']) ? 'true' : 'false' ?>" placeholder="چطور می‌توانیم کمک کنیم؟"><?= e($old['message'] ?? '') ?></textarea><?php if (isset($errors['message'])): ?><span class="form-error"><?= e($errors['message'][0]) ?></span><?php endif; ?></label>
            <div class="contact-form__footer"><span class="form-hint">با ارسال فرم، با سیاست حریم خصوصی موافقت می‌کنید.</span><button class="btn btn--primary btn--lg" type="submit">ارسال پیام</button></div>
        </form>
    </div>
</div></section>

<section class="section section--muted"><div class="container container--md"><header class="section__head"><div><span class="eyebrow">FAQ</span><h2>پرسش‌های پرتکرار</h2></div></header><div class="accordion" data-accordion="single"><?php foreach ([['contact-faq-1','چطور دوره مناسب را انتخاب کنم؟','هدف و سابقه خود را در فرم برای ما بنویسید تا تیم آموزشی مسیر مناسب را پیشنهاد کند.'],['contact-faq-2','آیا امکان همکاری با Mentoris وجود دارد؟','بله؛ پیشنهادهای تدریس، پژوهش و همکاری محتوایی بررسی می‌شوند.'],['contact-faq-3','پاسخ‌گویی چقدر زمان می‌برد؟','در روزهای کاری معمولاً طی ۲۴ تا ۴۸ ساعت پاسخ می‌دهیم.']] as $id => [$panel,$question,$answer]): ?><div class="accordion__item"><button class="accordion__trigger" aria-expanded="<?= $id === 0 ? 'true' : 'false' ?>" aria-controls="<?= e($panel) ?>"><span><?= e($question) ?></span><span class="accordion__icon">+</span></button><div class="accordion__panel <?= $id === 0 ? 'is-open' : '' ?>" id="<?= e($panel) ?>" aria-hidden="<?= $id === 0 ? 'false' : 'true' ?>"><div><p><?= e($answer) ?></p></div></div></div><?php endforeach; ?></div></div></section>
