<section class="page-hero courses-hero"><div class="container page-hero__content"><span class="eyebrow">Mentoris Courses</span><h1>دوره‌هایی برای <span class="text-gradient">یادگیری قابل استفاده</span></h1><p>از مبانی تا مهارت‌های پیشرفته؛ دوره‌هایی ساختاریافته با مدرس متخصص، تمرین و مسیر ادامه روشن.</p><div class="courses-hero__stats"><span><strong><?= count($courses) ?></strong> دوره</span><span><strong><?= count($categories) ?></strong> دسته‌بندی</span><span><strong><?= count(array_filter($courses, fn ($course) => $course['status'] === 'active')) ?></strong> دوره فعال</span></div></div></section>

<section class="section courses-catalog"><div class="container">
    <div class="course-filters surface" data-reveal>
        <label class="input-group"><span class="sr-only">جستجوی دوره</span><span class="input-group__icon">⌕</span><input class="form-control" type="search" placeholder="جستجو در عنوان، مدرس یا موضوع دوره..." data-course-search></label>
        <div class="course-filter-block"><span>دسته‌بندی</span><div class="program-filter-chips" role="group" aria-label="فیلتر دسته‌بندی"><button class="filter-chip is-active" data-course-category="all">همه</button><?php foreach ($categories as $key => $label): ?><button class="filter-chip" data-course-category="<?= e($key) ?>"><?= e($label) ?></button><?php endforeach; ?></div></div>
        <div class="course-filter-selects"><label><span class="form-label">وضعیت</span><select class="form-select" data-course-status><option value="all">همه وضعیت‌ها</option><?php foreach ($statuses as $key => $label): ?><option value="<?= e($key) ?>"><?= e($label) ?></option><?php endforeach; ?></select></label><label><span class="form-label">شیوه اجرا</span><select class="form-select" data-course-type><option value="all">همه شیوه‌ها</option><option value="آنلاین">آنلاین</option><option value="حضوری">حضوری</option><option value="هیبرید">هیبرید</option></select></label></div>
    </div>
    <div class="course-results"><p class="muted" aria-live="polite"><span data-course-count><?= count($courses) ?></span> دوره یافت شد</p><button class="btn btn--ghost btn--sm" type="button" data-course-reset>پاک‌کردن فیلترها</button></div>
    <div class="grid grid--3 courses-grid" data-course-grid><?php foreach ($courses as $course): ?><div data-course-item data-course-category-value="<?= e($course['category_slug']) ?>" data-course-status-value="<?= e($course['status']) ?>" data-course-type-value="<?= e($course['type']) ?>" data-course-text="<?= e($course['title'] . ' ' . $course['subtitle'] . ' ' . $course['description'] . ' ' . ($course['instructor']['name'] ?? '')) ?>"><?php require view_path('components/cards/course-card.php'); ?></div><?php endforeach; ?></div>
    <div class="empty-state" data-course-empty hidden><span>⌕</span><h3>دوره‌ای پیدا نشد</h3><p>عبارت جستجو یا فیلترهای دیگری را امتحان کنید.</p></div>
</div></section>

<section class="section section--muted"><div class="container"><div class="public-cta"><span class="eyebrow">Need Guidance?</span><h2>برای انتخاب دوره مطمئن نیستید؟</h2><p>اگر دنبال یک مسیر چندمرحله‌ای هستید، Programها را ببینید؛ برای انتخاب دقیق‌تر هم می‌توانید با تیم آکادمی گفتگو کنید.</p><div class="cluster"><a class="btn btn--primary btn--lg" href="/programs">مشاهده Programها</a><a class="btn btn--ghost btn--lg" href="/contact?subject=course">راهنمای انتخاب دوره</a></div></div></div></section>
