<?php $courseProgress = $course['capacity'] > 0 ? min(100, (int) round(($course['enrolled'] / $course['capacity']) * 100)) : 0; ?>
<section class="course-detail-hero course-detail-hero--<?= e($course['tone']) ?>"><div class="container course-detail-hero__grid">
    <div class="stack" data-reveal><div class="breadcrumb"><a href="/courses">دوره‌ها</a><span>←</span><a href="/academy/<?= e($course['line']['slug']) ?>"><?= e($course['line']['title']) ?></a></div><div class="cluster"><span class="badge badge--brand"><?= e($course['category']) ?></span><span class="course-status course-status--<?= e($course['status']) ?>"><?= e($course['status_label']) ?></span></div><h1><?= e($course['title']) ?></h1><p class="course-detail-subtitle ltr"><?= e($course['subtitle']) ?></p><p class="course-detail-lead"><?= e($course['description']) ?></p><div class="course-detail-facts"><span><small>مدت دوره</small><strong><?= e($course['duration']) ?></strong></span><span><small>برنامه زمانی</small><strong><?= e($course['schedule']) ?></strong></span><span><small>شیوه اجرا</small><strong><?= e($course['type']) ?></strong></span><span><small>سطح</small><strong><?= e($course['level']) ?></strong></span></div></div>
    <aside class="course-enroll-card" data-reveal><span class="eyebrow">Course Enrollment</span><div class="course-enroll-card__price"><small>هزینه دوره</small><strong><?= e($course['price']) ?></strong></div><div class="course-seat"><div><span><?= e((string) $course['enrolled']) ?> ثبت‌نام</span><strong><?= e((string) $course['available']) ?> جای خالی</strong></div><div class="event-capacity__track"><span style="width:<?= $courseProgress ?>%"></span></div><small>ظرفیت کل <?= e((string) $course['capacity']) ?> نفر</small></div>
        <?php if ($course['can_enroll']): ?><a class="btn btn--primary btn--lg w-full" href="/checkout/course/<?= e($course['slug']) ?>">ثبت‌نام و پرداخت</a><small>ظرفیت در Checkout برای ۱۵ دقیقه رزرو می‌شود.</small>
        <?php elseif ($course['status'] === 'coming-soon'): ?><a class="btn btn--secondary btn--lg w-full" href="/contact?subject=course-notify&amp;course=<?= e($course['slug']) ?>">اطلاع از شروع ثبت‌نام</a><small>زمان دقیق دوره به‌زودی اعلام می‌شود.</small>
        <?php elseif ($course['status'] === 'full'): ?><span class="course-enroll-card__notice">ظرفیت این دوره تکمیل شده است.</span><a class="btn btn--ghost w-full" href="/contact?subject=course-waitlist&amp;course=<?= e($course['slug']) ?>">عضویت در فهرست انتظار</a>
        <?php else: ?><span class="course-enroll-card__notice">این دوره پایان یافته است.</span><a class="btn btn--ghost w-full" href="/courses">مشاهده دوره‌های فعال</a><?php endif; ?>
    </aside>
</div></section>

<nav class="program-anchor-nav" aria-label="بخش‌های دوره"><div class="container"><a href="#overview">معرفی</a><a href="#audience">مخاطبان</a><a href="#curriculum">سرفصل‌ها</a><a href="#instructor">مدرس</a><a href="#certificate">گواهی</a><a href="#faq">سؤالات متداول</a></div></nav>

<section class="section" id="overview"><div class="container course-overview"><div class="stack" data-reveal><span class="eyebrow">About The Course</span><h2>درباره دوره</h2><p><?= e($course['description']) ?></p><blockquote>این دوره بخشی از لاین «<?= e($course['line']['title']) ?>» است و با رویکرد یادگیری کاربردی Mentoris طراحی شده است.</blockquote></div><div class="course-overview__method" data-reveal><span>01</span><h3>یادگیری مفهومی</h3><span>02</span><h3>نمونه و تمرین</h3><span>03</span><h3>بازخورد متخصص</h3><span>04</span><h3>برنامه ادامه مسیر</h3></div></div></section>

<section class="section section--muted" id="audience"><div class="container course-audience"><div class="stack" data-reveal><span class="eyebrow">Target Audience</span><h2>این دوره برای چه کسانی مناسب است؟</h2><p>اگر در یکی از گروه‌های زیر هستید، محتوای دوره با نیازهای یادگیری شما هم‌راستاست.</p></div><ul class="check-list course-audience__list" data-reveal><?php foreach ($course['audience'] as $item): ?><li><?= e($item) ?></li><?php endforeach; ?></ul></div></section>

<section class="section" id="curriculum"><div class="container container--md"><header class="section__head"><div><span class="eyebrow">Course Curriculum</span><h2>سرفصل‌های دوره</h2><p><?= count($course['curriculum']) ?> بخش ساختاریافته با آموزش، تمرین و بازخورد.</p></div></header><div class="accordion course-curriculum" data-accordion="single"><?php foreach ($course['curriculum'] as $index => $module): $panelId = 'course-module-' . $index; ?><div class="accordion__item"><button class="accordion__trigger" type="button" aria-expanded="<?= $index === 0 ? 'true' : 'false' ?>" aria-controls="<?= e($panelId) ?>"><span><small>0<?= $index + 1 ?></small><?= e($module['title']) ?></span><span class="course-module-duration"><?= e($module['duration']) ?></span><span class="accordion__icon">+</span></button><div class="accordion__panel <?= $index === 0 ? 'is-open' : '' ?>" id="<?= e($panelId) ?>" aria-hidden="<?= $index === 0 ? 'false' : 'true' ?>"><div><p><?= e($module['description']) ?></p></div></div></div><?php endforeach; ?></div></div></section>

<section class="section section--muted" id="instructor"><div class="container course-instructor" data-reveal><div class="mentor-card__portrait mentor-card__portrait--<?= e($course['instructor']['tone']) ?>"><span><?= e($course['instructor']['initials']) ?></span></div><div class="stack"><span class="eyebrow">Course Instructor</span><h2><?= e($course['instructor']['name']) ?></h2><div class="cluster"><span class="badge badge--neutral"><?= e($course['instructor']['role']) ?></span><span class="badge badge--neutral"><?= e($course['instructor']['specialty']) ?></span></div><p><?= e($course['instructor_bio']) ?></p><a class="btn btn--ghost btn--sm" href="/mentors">مشاهده همه اساتید</a></div></div></section>

<section class="section" id="certificate"><div class="container course-certificate"><div class="course-certificate__visual" aria-hidden="true"><span>✓</span><strong>Mentoris</strong><small>Certificate of Completion</small></div><div class="stack" data-reveal><span class="eyebrow">Certificate</span><h2>گواهی پایان دوره</h2><p><?= e($course['certificate']) ?> پس از حضور مؤثر، تکمیل تمرین‌ها و ارزیابی پایانی صادر می‌شود.</p><ul class="check-list"><li>نام دوره، مدرس و مدت آموزش</li><li>کد رهگیری داخلی Mentoris</li><li>نسخه دیجیتال قابل دریافت</li></ul></div></div></section>

<section class="section section--muted" id="faq"><div class="container container--md"><header class="section__head"><div><span class="eyebrow">Course FAQ</span><h2>سؤالات متداول</h2></div></header><div class="accordion" data-accordion="single"><?php foreach ($course['faq'] as $index => $faq): $faqId = 'course-faq-' . $index; ?><div class="accordion__item"><button class="accordion__trigger" type="button" aria-expanded="<?= $index === 0 ? 'true' : 'false' ?>" aria-controls="<?= e($faqId) ?>"><span><?= e($faq['question']) ?></span><span class="accordion__icon">+</span></button><div class="accordion__panel <?= $index === 0 ? 'is-open' : '' ?>" id="<?= e($faqId) ?>" aria-hidden="<?= $index === 0 ? 'false' : 'true' ?>"><div><p><?= e($faq['answer']) ?></p></div></div></div><?php endforeach; ?></div></div></section>

<?php if ($course['related_programs']): ?><section class="section"><div class="container"><header class="section__head"><div><span class="eyebrow">Related Programs</span><h2>Programهای مرتبط</h2><p>اگر به یک مسیر چندمرحله‌ای نیاز دارید، این دوره در Programهای زیر قرار گرفته است.</p></div></header><div class="grid grid--3"><?php foreach ($course['related_programs'] as $program): $program['line_title'] = $course['line']['title']; require view_path('components/cards/program-card.php'); endforeach; ?></div></div></section><?php endif; ?>

<section class="section section--muted"><div class="container"><div class="public-cta"><span class="eyebrow">Your Next Course</span><h2>برای شروع آماده‌اید؟</h2><p>جزئیات دوره را بررسی کنید و ثبت‌نام خود را از مسیر امن Checkout نهایی کنید.</p><div class="cluster"><a class="btn btn--primary btn--lg" href="<?= $course['can_enroll'] ? '/checkout/course/' . e($course['slug']) : '/courses' ?>"><?= $course['can_enroll'] ? 'ثبت‌نام و پرداخت' : 'مشاهده دوره‌ها' ?></a><a class="btn btn--ghost btn--lg" href="/programs">مشاهده Programها</a></div></div></div></section>
