<?php $progress = $event['capacity'] > 0 ? min(100, (int) round(($event['registered'] / $event['capacity']) * 100)) : 0; ?>
<section class="event-detail-hero event-detail-hero--<?= e($event['tone']) ?>"><div class="container event-detail-hero__grid">
    <div class="stack" data-reveal><div class="breadcrumb"><a href="/events">رویدادها</a><span>←</span><a href="/academy/<?= e($event['line']['slug']) ?>"><?= e($event['line']['title']) ?></a></div><span class="event-status event-status--<?= e($event['status']) ?>"><?= e($event['status_label']) ?></span><h1><?= e($event['title']) ?></h1><p class="event-detail-lead"><?= e($event['short_description']) ?></p><div class="event-detail-facts"><span><small>تاریخ و ساعت</small><strong><?= e($event['date']) ?> · <?= e($event['time']) ?></strong></span><span><small>شیوه برگزاری</small><strong><?= e($event['mode_label']) ?></strong></span><span><small>مکان</small><strong><?= e($event['location']) ?></strong></span><span><small>مدرس</small><strong><?= e($event['instructor']['name'] ?? 'Mentoris Academy') ?></strong></span></div></div>
    <aside class="event-registration" id="register" data-reveal>
        <span class="eyebrow">Event Registration</span><h2>ثبت‌نام در رویداد</h2>
        <div class="event-registration__capacity"><div><span><?= e((string) $event['registered']) ?> ثبت‌نام</span><strong><?= e((string) $event['available']) ?> جای خالی</strong></div><div class="event-capacity__track"><span style="width:<?= $progress ?>%"></span></div><small>ظرفیت کل: <?= e((string) $event['capacity']) ?> نفر</small></div>
        <?php if ($success): ?><div class="alert alert--success" role="status"><strong>درخواست شما ثبت شد.</strong><p>جزئیات هماهنگی از طریق ایمیل برایتان ارسال خواهد شد.</p></div><?php endif; ?>
        <?php if ($notice): ?><div class="alert alert--danger" role="alert"><strong><?= e($notice) ?></strong></div><?php endif; ?>
        <?php if ($errors): ?><div class="alert alert--danger" role="alert"><strong>لطفاً اطلاعات فرم را بررسی کنید.</strong></div><?php endif; ?>
        <?php if ($event['can_register'] && !$success): ?><form class="stack" method="post" action="/events/<?= e($event['slug']) ?>/register"><?= csrf_field() ?><label class="form-group"><span class="form-label">نام و نام خانوادگی *</span><input class="form-control" name="name" value="<?= e($old['name'] ?? '') ?>" required><?php if (isset($errors['name'])): ?><span class="form-error"><?= e($errors['name'][0]) ?></span><?php endif; ?></label><label class="form-group"><span class="form-label">ایمیل *</span><input class="form-control ltr" type="email" name="email" value="<?= e($old['email'] ?? '') ?>" required><?php if (isset($errors['email'])): ?><span class="form-error"><?= e($errors['email'][0]) ?></span><?php endif; ?></label><div class="grid grid--2"><label class="form-group"><span class="form-label">شماره تماس *</span><input class="form-control ltr" name="phone" value="<?= e($old['phone'] ?? '') ?>" required></label><label class="form-group"><span class="form-label">نقش حرفه‌ای *</span><select class="form-select" name="role" required><option value="">انتخاب کنید</option><?php foreach (['دانشجو','روان‌شناس / درمانگر','پژوهشگر','مدیر / متخصص منابع انسانی','سایر'] as $role): ?><option <?= ($old['role'] ?? '') === $role ? 'selected' : '' ?>><?= e($role) ?></option><?php endforeach; ?></select></label></div><button class="btn btn--primary btn--lg w-full" type="submit">ثبت درخواست</button><small class="event-form-note">ثبت اولیه رایگان است؛ اطلاعات پرداخت یا تأیید نهایی در مرحله بعد اعلام می‌شود.</small></form>
        <?php elseif (!$success): ?><div class="event-state-message event-state-message--<?= e($event['status']) ?>"><strong><?= e($event['status_label']) ?></strong><p><?= match ($event['status']) { 'upcoming' => 'زمان بازشدن ثبت‌نام به‌زودی اعلام می‌شود.', 'full' => 'ظرفیت این رویداد تکمیل شده است.', 'completed' => 'این رویداد برگزار شده و ثبت‌نام آن بسته است.', 'canceled' => 'این رویداد لغو شده است.', default => 'ثبت‌نام در حال حاضر فعال نیست.' } ?></p><a class="btn btn--ghost btn--sm" href="/events">مشاهده رویدادهای دیگر</a></div><?php endif; ?>
    </aside>
</div></section>

<section class="section"><div class="container event-overview"><div class="stack" data-reveal><span class="eyebrow">About The Event</span><h2>درباره رویداد</h2><p class="event-description"><?= e($event['description']) ?></p><h3>آنچه در این رویداد تجربه می‌کنید</h3><ul class="check-list"><?php foreach ($event['highlights'] as $item): ?><li><?= e($item) ?></li><?php endforeach; ?></ul></div><aside class="event-line-card" data-reveal><span><?= e($event['line']['icon']) ?></span><small>Academy Line</small><h3><?= e($event['line']['title']) ?></h3><p><?= e($event['line']['description']) ?></p><a class="btn btn--secondary btn--sm" href="/academy/<?= e($event['line']['slug']) ?>">مشاهده لاین</a></aside></div></section>

<?php if ($event['related_programs']): ?><section class="section section--muted"><div class="container"><header class="section__head"><div><span class="eyebrow">Related Programs</span><h2>مسیرهای مرتبط با این رویداد</h2></div></header><div class="grid grid--3"><?php foreach ($event['related_programs'] as $program): $program['line_title'] = $event['line']['title']; require view_path('components/cards/program-card.php'); endforeach; ?></div></div></section><?php endif; ?>

<section class="section"><div class="container"><div class="public-cta"><span class="eyebrow">Mentoris Community</span><h2>گفتگو بعد از رویداد ادامه دارد</h2><p>به جامعه حرفه‌ای منتوریس بپیوندید و از رویدادهای اعضا و منابع منتخب باخبر شوید.</p><a class="btn btn--primary btn--lg" href="/community#join">عضویت در Community</a></div></div></section>
