<?php
$copy = [
    'fa'=>['back'=>'رویدادها','date'=>'تاریخ و ساعت','mode'=>'شیوه برگزاری','place'=>'مکان','host'=>'برگزارکننده','register'=>'فرم ثبت‌نام اولیه','about'=>'درباره رویداد','experience'=>'آنچه در این رویداد تجربه می‌کنید','privacy'=>'لینک ثبت‌نام در Google Forms باز می‌شود. اطلاعات شما مطابق سیاست همان سرویس و برای بررسی درخواست ثبت‌نام دریافت خواهد شد.'],
    'ar'=>['back'=>'الفعاليات','date'=>'التاريخ والوقت','mode'=>'طريقة الحضور','place'=>'المكان','host'=>'المنظّم','register'=>'نموذج التسجيل الأولي','about'=>'عن الفعالية','experience'=>'ما ستختبره في اللقاء','privacy'=>'يُفتح التسجيل في نماذج Google وتخضع البيانات لسياسة ذلك المزود.'],
    'ku'=>['back'=>'بۆنەکان','date'=>'ڕێکەوت و کات','mode'=>'شێوازی بەشداری','place'=>'شوێن','host'=>'ڕێکخەر','register'=>'فۆڕمی تۆمارکردنی سەرەتایی','about'=>'دەربارەی بۆنە','experience'=>'ئەوەی لەم بۆنەیە ئەزموونی دەکەن','privacy'=>'تۆمارکردن لە Google Forms دەکرێتەوە و زانیارییەکان بە پێی سیاسەتی ئەو خزمەتگوزارییە وەردەگیرێن.'],
    'en'=>['back'=>'Events','date'=>'Date and time','mode'=>'Format','place'=>'Location','host'=>'Hosted by','register'=>'Initial registration form','about'=>'About the event','experience'=>'What to expect','privacy'=>'Registration opens in Google Forms. Your information is handled under that provider’s policy and used to review your application.'],
][locale()];
?>
<section class="event-detail-hero event-detail-hero--<?= e($event['tone']) ?>"><div class="container event-detail-hero__grid">
    <div class="stack" data-reveal><div class="breadcrumb"><a href="/events"><?= e($copy['back']) ?></a><span>←</span><span><?= e($event['type']) ?></span></div><span class="event-status event-status--<?= e($event['status']) ?>"><?= e($event['status_label']) ?></span><h1><?= e($event['title']) ?></h1><p class="event-detail-lead"><?= e($event['short_description']) ?></p><div class="event-detail-facts"><span><small><?= e($copy['date']) ?></small><strong><?= e($event['date']) ?> · <?= e($event['time']) ?></strong></span><span><small><?= e($copy['mode']) ?></small><strong><?= e($event['mode_label']) ?></strong></span><span><small><?= e($copy['place']) ?></small><strong><?= e($event['location']) ?></strong></span><span><small><?= e($copy['host']) ?></small><strong>Mentoris Academy</strong></span></div></div>
    <aside class="event-registration" id="register" data-reveal><span class="eyebrow">Registration</span><h2><?= e($copy['register']) ?></h2><div class="event-registration__limited"><span aria-hidden="true">◫</span><strong><?= e($event['capacity_label']) ?></strong></div><p><?= e($event['registration_note']) ?></p><a class="btn btn--primary btn--lg w-full" href="<?= e($event['external_registration_url']) ?>" target="_blank" rel="noopener noreferrer"><?= e($copy['register']) ?> ↗</a><small class="event-form-note"><?= e($copy['privacy']) ?></small></aside>
</div></section>

<section class="section"><div class="container event-overview"><article class="stack" data-reveal><span class="eyebrow">About The Event</span><h2><?= e($copy['about']) ?></h2><p class="event-description"><?= e($event['description']) ?></p><h3><?= e($copy['experience']) ?></h3><ul class="check-list"><?php foreach ($event['highlights'] as $item): ?><li><?= e($item) ?></li><?php endforeach; ?></ul></article><aside class="event-founder-mini surface" data-reveal><img src="<?= asset($event['instructor']['image']) ?>" alt="<?= e($event['instructor']['name']) ?>" width="1024" height="1536"><div><small>Mentoris Academy</small><strong><?= e($event['instructor']['name']) ?></strong><span><?= e($event['instructor']['role']) ?></span></div></aside></div></section>

<section class="section section--muted"><div class="container"><div class="public-cta"><span class="eyebrow">Mentoris Community</span><h2><?= e(t('footer.tagline')) ?></h2><div class="cluster"><a class="btn btn--primary" href="/community"><?= e(t('nav.community')) ?></a><a class="btn btn--ghost" href="/contact"><?= e(t('nav.contact')) ?></a></div></div></div></section>
