<section class="page-hero events-hero"><div class="container page-hero__content"><span class="eyebrow">Mentoris Events</span><h1>یادگیری در دل <span class="text-gradient">تجربه و گفتگو</span></h1><p>کارگاه‌ها، نشست‌ها و حلقه‌های تخصصی برای تمرین آموخته‌ها و ساختن ارتباط‌های حرفه‌ای.</p><div class="events-hero__stats"><span><strong><?= count($events) ?></strong> رویداد</span><span><strong><?= count(array_filter($events, fn ($item) => $item['can_register'])) ?></strong> ثبت‌نام باز</span><span><strong>۳</strong> شیوه اجرا</span></div></div></section>

<section class="section events-catalog"><div class="container">
    <div class="event-filters surface" data-reveal>
        <label class="input-group"><span class="sr-only">جستجوی رویداد</span><span class="input-group__icon">⌕</span><input class="form-control" type="search" placeholder="جستجو در عنوان، مدرس یا موضوع..." data-event-search></label>
        <div class="event-filter-row"><div class="program-filter-chips" role="group" aria-label="فیلتر وضعیت"><button class="filter-chip is-active" data-event-status="all">همه</button><?php foreach ($statuses as $key => $label): ?><button class="filter-chip" data-event-status="<?= e($key) ?>"><?= e($label) ?></button><?php endforeach; ?></div><label><span class="sr-only">شیوه برگزاری</span><select class="form-select" data-event-mode><option value="all">همه شیوه‌ها</option><option value="online">آنلاین</option><option value="offline">حضوری</option><option value="hybrid">هیبرید</option></select></label></div>
    </div>
    <p class="program-results muted" aria-live="polite"><span data-event-count><?= count($events) ?></span> رویداد یافت شد</p>
    <div class="grid grid--3 events-grid" data-event-grid><?php foreach ($events as $event): ?><div data-event-item data-event-status-value="<?= e($event['status']) ?>" data-event-mode-value="<?= e($event['mode']) ?>" data-event-text="<?= e($event['title'] . ' ' . $event['type'] . ' ' . ($event['instructor']['name'] ?? '') . ' ' . $event['short_description']) ?>"><?php require view_path('components/cards/event-card.php'); ?></div><?php endforeach; ?></div>
    <div class="empty-state" data-event-empty hidden><span>⌕</span><h3>رویدادی پیدا نشد</h3><p>فیلترها یا عبارت جستجو را تغییر دهید.</p></div>
</div></section>

<section class="section section--muted"><div class="container"><div class="community-banner"><div class="stack"><span class="eyebrow">Community First</span><h2>رویدادها نقطه شروع ارتباط‌اند</h2><p>در Community منتوریس، گفتگو و یادگیری بعد از پایان رویداد هم ادامه پیدا می‌کند.</p><div class="cluster"><a class="btn btn--primary" href="/community#join">عضویت در Community</a><a class="btn btn--ghost" href="/community">آشنایی بیشتر</a></div></div><div class="community-orbit"><span>◎</span><small>Learn · Connect · Grow</small></div></div></div></section>
