<?php
$copy = [
    'fa'=>['back'=>'رویدادها','date'=>'تاریخ و ساعت','mode'=>'شیوه برگزاری','place'=>'مکان','host'=>'برگزارکننده','register'=>'فرم ثبت‌نام اولیه','about'=>'درباره رویداد','experience'=>'آنچه در این رویداد تجربه می‌کنید'],
    'ar'=>['back'=>'الفعاليات','date'=>'التاريخ والوقت','mode'=>'طريقة الحضور','place'=>'المكان','host'=>'المنظّم','register'=>'نموذج التسجيل الأولي','about'=>'عن الفعالية','experience'=>'ما ستختبره في اللقاء'],
    'ku'=>['back'=>'بۆنەکان','date'=>'ڕێکەوت و کات','mode'=>'شێوازی بەشداری','place'=>'شوێن','host'=>'ڕێکخەر','register'=>'فۆڕمی تۆمارکردنی سەرەتایی','about'=>'دەربارەی بۆنە','experience'=>'ئەوەی لەم بۆنەیە ئەزموونی دەکەن'],
    'en'=>['back'=>'Events','date'=>'Date and time','mode'=>'Format','place'=>'Location','host'=>'Hosted by','register'=>'Initial registration form','about'=>'About the event','experience'=>'What to expect'],
][locale()];
?>
<section class="event-detail-hero event-detail-hero--<?= e($event['tone']) ?>"><div class="container event-detail-hero__grid">
    <div class="stack" data-reveal><div class="breadcrumb"><a href="/events"><?= e($copy['back']) ?></a><span><?= icon('arrow-left') ?></span><span><?= e($event['type']) ?></span></div><span class="event-status event-status--<?= e($event['status']) ?>"><?= e($event['can_register'] && !$registrationReady ? \App\Services\PublicContentService::eventStatusLabels()['upcoming'] : $event['status_label']) ?></span><h1><?= e($event['title']) ?></h1><p class="event-detail-lead"><?= e($event['short_description']) ?></p><div class="event-detail-facts"><span><small><?= e($copy['date']) ?></small><strong><?= e($event['date']) ?> · <?= e($event['time']) ?></strong></span><span><small><?= e($copy['mode']) ?></small><strong><?= e($event['mode_label']) ?></strong></span><span><small><?= e($copy['place']) ?></small><strong><?= e($event['location']) ?></strong></span><span><small><?= e($copy['host']) ?></small><strong>Mentoris Academy</strong></span></div></div>
    <aside class="event-registration" id="register" data-reveal><?php if (!empty($event['image'])): ?><img class="event-registration__poster" src="<?= asset($event['image']) ?>" alt="پوستر <?= e($event['title']) ?>" width="1080" height="1920"><?php endif; ?><div class="event-registration__body"><span class="eyebrow">Mentoris / Event</span><h2><?= $event['can_register'] ? 'درخواست حضور' : 'وضعیت رویداد' ?></h2><div class="event-registration__limited"><span><?= icon('calendar') ?></span><strong><?= e($event['capacity_label']) ?></strong></div><p><?= e($event['status'] === 'completed' ? 'این نشست برگزار شده است.' : ($registrationReady ? $event['registration_note'] : 'زمان دقیق و امکان درخواست حضور به‌زودی اعلام می‌شود.')) ?></p><?php if ($event['slug'] === 'therapists-circle-second'): ?><p><a href="https://www.google.com/maps/search/?api=1&amp;query=<?= rawurlencode($event['location']) ?>" target="_blank" rel="noopener noreferrer">جست‌وجوی محل در نقشه <?= icon('arrow-left') ?></a></p><?php endif; ?>
    <?php if ($success): ?><div class="alert alert--success" role="status">درخواست شما ثبت شد. وضعیت و جزئیات نهایی پس از اعلام رسمی اطلاع‌رسانی می‌شود.</div><?php endif; ?>
    <?php if ($notice): ?><div class="alert alert--danger" role="alert"><?= e($notice) ?></div><?php endif; ?>
    <?php if ($event['can_register'] && $registrationReady): ?><form class="stack" method="post" action="/events/<?= e($event['slug']) ?>/register"><?= csrf_field() ?>
        <label class="form-group"><span class="form-label">نام و نام خانوادگی *</span><input class="form-control" name="name" autocomplete="name" maxlength="80" value="<?= e($old['name'] ?? '') ?>" required><?php if (isset($errors['name'])): ?><small class="form-error">نام معتبر وارد کنید.</small><?php endif; ?></label>
        <label class="form-group"><span class="form-label">شماره موبایل *</span><input class="form-control ltr" type="tel" name="phone" autocomplete="tel" inputmode="tel" pattern="(?:\+98|0)?9[0-9]{9}" value="<?= e($old['phone'] ?? '') ?>" required><?php if (isset($errors['phone'])): ?><small class="form-error">شماره موبایل ۱۱ رقمی معتبر وارد کنید.</small><?php endif; ?></label>
        <label class="form-group"><span class="form-label">شهر محل سکونت *</span><input class="form-control" name="city" maxlength="80" value="<?= e($old['city'] ?? '') ?>" required><?php if (isset($errors['city'])): ?><small class="form-error">شهر را وارد کنید.</small><?php endif; ?></label>
        <button class="btn btn--primary btn--lg w-full" type="submit">ثبت درخواست حضور</button>
    </form><?php endif; ?><small class="event-form-note">برای ساخت پنل و تکمیل پروفایل تخصصی می‌توانید جداگانه <a href="/register">عضو منتوریس شوید</a>.</small></div></aside>
</div></section>

<section class="section"><div class="container event-overview"><article class="stack" data-reveal><span class="eyebrow">About The Event</span><h2><?= e($copy['about']) ?></h2><p class="event-description"><?= e($event['description']) ?></p><h3><?= e($copy['experience']) ?></h3><ul class="check-list"><?php foreach ($event['highlights'] as $item): ?><li><?= e($item) ?></li><?php endforeach; ?></ul></article><aside class="event-founder-mini surface" data-reveal><img src="<?= asset($event['instructor']['image']) ?>" alt="<?= e($event['instructor']['name']) ?>" width="1024" height="1536"><div><small>Mentoris Academy</small><strong><?= e($event['instructor']['name']) ?></strong><span><?= e($event['instructor']['role']) ?></span></div></aside></div></section>

<section class="section section--muted"><div class="container"><div class="public-cta"><span class="eyebrow">Mentoris Community</span><h2><?= e(t('footer.tagline')) ?></h2><div class="cluster"><a class="btn btn--primary" href="/community"><?= e(t('nav.community')) ?></a><a class="btn btn--ghost" href="/contact"><?= e(t('nav.contact')) ?></a></div></div></div></section>
