<section class="live-hero"><div class="container live-hero__inner"><div><span class="live-kicker">MENTORIS / FEEDBACK</span><h1>از گفت‌وگو تا تمرین،<br><em>همراه شما می‌مانیم.</em></h1><p>صفحه همراه حلقه درمانگران؛ بازخوردتان را ثبت کنید، شیت تمرین را بردارید و به جامعه حرفه‌ای منتوریس بپیوندید.</p><div class="live-meta"><span><?= icon('pin') ?> باشگاه فرهنگیان تبریز</span><span><?= icon('clock') ?> ساعت ۱۸</span><a href="https://www.google.com/maps/search/?api=1&amp;query=<?= rawurlencode('باشگاه فرهنگیان تبریز') ?>" target="_blank" rel="noopener noreferrer">جست‌وجو در نقشه <?= icon('arrow-left') ?></a></div></div><div class="live-mark" aria-hidden="true"><span>م</span><small>حلقه درمانگران<br>منتوریس</small></div></div></section>
<section class="section live-actions"><div class="container"><div class="live-section-head"><span class="eyebrow">مسیر شما در نشست</span><h2>سه قدم کوتاه، یک مسیر ادامه‌دار</h2></div><div class="live-card-grid">
<a class="live-card" href="<?= $signup ? '#feedback' : '#access' ?>"><span class="live-card__number">۰۱</span><span class="live-card__icon"><?= icon('message') ?></span><h3>بازخورد نشست</h3><p>از کیفیت محتوا، میزبانی و چالش بالینی امروزتان بگویید.</p><strong>تکمیل فرم <?= icon('arrow-left') ?></strong></a>
<a class="live-card" href="<?= $signup ? '/feedback/toolbox' : '#access' ?>"><span class="live-card__number">۰۲</span><span class="live-card__icon"><?= icon('file') ?></span><h3>جعبه‌ابزار اختصاصی</h3><p>شیت خودارزیابی لنگراندازی و راهنمای کوتاه مدل GRACE را دریافت کنید.</p><strong><?= !empty($profileComplete) ? 'دریافت PDF' : 'ورود و تکمیل پروفایل' ?> <?= icon('arrow-left') ?></strong></a>
<a class="live-card" href="/community#join"><span class="live-card__number">۰۳</span><span class="live-card__icon"><?= icon('users') ?></span><h3>عضویت رایگان در کلاب</h3><p>گفت‌وگو و یادگیری را در جامعه حرفه‌ای منتوریس ادامه دهید.</p><strong>آشنایی و عضویت <?= icon('arrow-left') ?></strong></a>
</div></div></section>
<?php if (!$signup): ?><section class="section live-gate" id="access"><div class="container container--sm"><div class="live-gate__panel"><span class="eyebrow">بازخورد نشست‌های برگزارشده</span><h2>نشست خود را انتخاب کنید</h2><?php if(isset($errors['access'])):?><div class="alert alert--danger" role="alert"><?= e($errors['access']) ?></div><?php endif;?><?php if($feedbackReady):?>
<?php if($identity):?><form class="stack" method="post" action="/feedback/access"><?= csrf_field() ?><input type="hidden" name="member_access" value="1"><label class="form-group"><span class="form-label">نشست</span><select class="form-select" name="event"><?php foreach($events as $item):?><option value="<?= e($item['slug']) ?>" <?= $event['slug']===$item['slug'] ? 'selected' : '' ?>><?= e($item['title']) ?></option><?php endforeach;?></select></label><label class="check"><input type="checkbox" name="participated" value="1" required><span>در نشست انتخاب‌شده شرکت کرده‌ام و مایلم بازخورد بدهم.</span></label><button class="btn btn--primary">ورود به نظرسنجی</button></form><small>ثبت نظر، تأیید حضور یا ثبت‌نام جدید همایش نیست. وضعیت حضور و گواهی را برگزارکننده بررسی می‌کند.</small>
<?php else:?><p>برای ثبت نظر وارد حساب شوید. ساخت حساب بدون کد تأیید انجام می‌شود.</p><div class="member-form__actions"><a class="btn btn--primary" href="/login">ورود</a><a class="btn btn--secondary" href="/register">ساخت حساب</a></div><?php endif;?>
<?php if($hallCodeEnabled):?><details class="member-section"><summary>ورود با شمارهٔ ثبت‌شده و کد سالن</summary><form class="stack member-section__body" method="post" action="/feedback/access"><?= csrf_field() ?><label class="form-group"><span class="form-label">نشست</span><select class="form-select" name="event"><?php foreach($events as $item):?><option value="<?= e($item['slug']) ?>" <?= $event['slug']===$item['slug'] ? 'selected' : '' ?>><?= e($item['title']) ?></option><?php endforeach;?></select></label><label class="form-group"><span class="form-label">شماره موبایل</span><input class="form-control ltr" type="tel" name="phone" autocomplete="tel" required></label><label class="form-group"><span class="form-label">کد سالن</span><input class="form-control ltr" name="access_code" autocomplete="off" required></label><button class="btn btn--secondary">ورود با کد سالن</button></form></details><?php endif;?>
<?php else:?><p>نظرسنجی پس از به‌روزرسانی پایگاه داده فعال می‌شود.</p><?php endif;?></div></div></section><?php else: ?>
<section class="section live-feedback" id="feedback"><div class="container container--sm"><div class="live-section-head"><span class="eyebrow">Your Voice</span><h2>بازخورد شما مسیر بعدی ما را می‌سازد</h2><p><?= e($event['title']) ?></p><a href="/feedback?event=<?= e($event['slug'] === 'therapists-circle-second' ? 'therapists-circle-tabriz' : 'therapists-circle-second') ?>">انتخاب نشست دیگر</a><p>سلام <?= e($signup['name']) ?>، پاسخ‌ها به بهبود نشست‌های بعدی کمک می‌کنند.</p><p>برای دریافت فایل کارگاه، حساب خود را بسازید و پروفایل تخصصی را کامل کنید. ثبت بازخورد نیز برای صدور گواهی لازم است.</p></div>
<?php if ($feedback): ?><div class="live-gate__panel"><div class="alert alert--success" role="status">بازخورد شما ثبت شده است. سپاس از همراهی‌تان.</div><p>درخواست گواهی، پس از بررسی حضور و تکمیل پروفایل تخصصی در پنل پیگیری می‌شود.</p><a class="btn btn--secondary" href="/profile">رفتن به پروفایل تخصصی</a></div><?php else: ?>
<form class="live-gate__panel stack" method="post" action="/feedback/submit"><?= csrf_field() ?><?php if (isset($errors['feedback'])): ?><div class="alert alert--danger" role="alert"><?= e($errors['feedback']) ?></div><?php endif; ?>
<?php foreach (['content_rating'=>'مباحث این نشست چقدر کاربردی بود؟','hosting_rating'=>'کیفیت میزبانی و فضای گفت‌وگو را چطور ارزیابی می‌کنید؟'] as $field=>$label): ?><fieldset class="live-rating"><legend><?= e($label) ?></legend><div class="live-rating__options"><?php for ($rating=1; $rating<=5; $rating++): ?><label><input type="radio" name="<?= e($field) ?>" value="<?= $rating ?>" <?= (string) ($old[$field] ?? '') === (string) $rating ? 'checked' : '' ?> required><span><?= $rating ?></span></label><?php endfor; ?></div><?php if (isset($errors[$field])): ?><small class="form-error"><?= e($errors[$field]) ?></small><?php endif; ?></fieldset><?php endforeach; ?>
<label class="form-group"><span class="form-label">بزرگ‌ترین چالش فعلی شما در مسیر بالینی</span><select class="form-select" name="challenge" required><option value="">انتخاب کنید</option><?php foreach (['burnout'=>'فرسودگی و خستگی','technique'=>'ابهام در اجرای تکنیک‌ها','countertransference'=>'انتقال متقابل و اضطراب','supervision'=>'کمبود سوپرویژن منظم'] as $value=>$label): ?><option value="<?= e($value) ?>" <?= ($old['challenge'] ?? '') === $value ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select><?php if (isset($errors['challenge'])): ?><small class="form-error"><?= e($errors['challenge']) ?></small><?php endif; ?></label>
<label class="form-group"><span class="form-label">پیشنهاد یا نظر آزاد</span><textarea class="form-textarea" name="comment" maxlength="1000" rows="4"><?= e($old['comment'] ?? '') ?></textarea><?php if (isset($errors['comment'])): ?><small class="form-error"><?= e($errors['comment']) ?></small><?php endif; ?></label><button class="btn btn--primary btn--lg" type="submit">ثبت بازخورد</button></form><?php endif; ?>
</div></section><?php endif; ?>
