<section class="feedback-page"><div class="container container--sm"><header class="feedback-page__head"><span class="eyebrow">صدای شما برای ما مهم است</span><h1>نظر شما دربارهٔ نشست</h1><p>دو امتیاز کوتاه؛ کمتر از یک دقیقه.</p></header>
<nav class="feedback-event-tabs" aria-label="انتخاب نشست"><?php foreach($events as $i=>$item):?><a class="<?= $event['slug']===$item['slug'] ? 'is-active' : '' ?>" href="/feedback?event=<?= e($item['slug']) ?>">نشست <?= $i===0 ? 'اول' : 'دوم' ?></a><?php endforeach;?></nav><h2 class="feedback-event-title"><?= e($event['title']) ?></h2>
<?php if(!$feedbackReady):?><div class="alert alert--danger">نظرسنجی بعد از آماده‌شدن پایگاه داده فعال می‌شود.</div>
<?php elseif($feedback):?><div class="survey-success user-panel"><span><?= icon('check') ?></span><h2>ممنون که نظرتان را گفتید.</h2><p>بازخورد شما ثبت شده است.</p><a class="btn btn--primary" href="/resources">دریافت ابزارهای رایگان</a><a class="btn btn--ghost" href="/profile#community">جامعهٔ حرفه‌ای منتوریس</a></div>
<?php elseif($identity || $signup):?><form class="user-panel stack" method="post" action="/feedback/submit" data-survey-form><?= csrf_field() ?><input type="hidden" name="event" value="<?= e($event['slug']) ?>"><input type="hidden" name="member_access" value="1"><input type="hidden" name="participated" value="1">
<?php if($errors):?><div class="alert alert--danger" role="alert"><?php foreach($errors as $message):?><p><?= e($message) ?></p><?php endforeach;?></div><?php endif;?>
<?php foreach(['content_rating'=>'محتوای نشست چقدر برایتان مفید بود؟','hosting_rating'=>'فضا و میزبانی نشست چطور بود؟'] as $key=>$label):?><fieldset class="survey-rating"><legend><?= e($label) ?></legend><div><?php for($i=1;$i<=5;$i++):?><label><input type="radio" name="<?= e($key) ?>" value="<?= $i ?>" <?= (string)($old[$key] ?? '')===(string)$i ? 'checked' : '' ?> required><span><?= $i ?></span></label><?php endfor;?></div><p><span>۱ · ضعیف</span><span>۵ · عالی</span></p></fieldset><?php endforeach;?>
<details class="member-section"><summary>اگر مایلید، کمی بیشتر بگویید <small>اختیاری</small></summary><div class="member-section__body stack"><label class="form-group"><span class="form-label">چالش اصلی شما در مسیر حرفه‌ای</span><select class="form-select" name="challenge"><option value="none">ترجیح می‌دهم انتخاب نکنم</option><?php foreach(['burnout'=>'فرسودگی و خستگی','technique'=>'اجرای تکنیک‌ها','countertransference'=>'انتقال متقابل و اضطراب','supervision'=>'کمبود سوپرویژن'] as $key=>$label):?><option value="<?= $key ?>" <?= ($old['challenge'] ?? '')===$key ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach;?></select></label><label class="form-group"><span class="form-label">پیشنهاد شما</span><textarea class="form-textarea" name="comment" rows="3" maxlength="1000" placeholder="چه چیزی بهتر شود؟"><?= e($old['comment'] ?? '') ?></textarea></label></div></details>
<button class="btn btn--primary btn--lg w-full" type="submit">ارسال بازخورد</button><p data-save-status role="status" aria-live="polite"></p><small class="form-hint">با ارسال نظر، مشارکت خود در این نشست را اعلام می‌کنید. صدور گواهی به بررسی حضور وابسته است.</small></form>
<?php else:?><div class="user-panel stack"><h2>یک بار وارد شوید.</h2><p>نام و اطلاعاتتان از حساب خوانده می‌شود؛ فرم طولانی دیگری نداریم.</p><a class="btn btn--primary" href="/login">ورود و ثبت نظر</a><a class="btn btn--ghost" href="/register">ساخت حساب رایگان</a></div><?php endif;?>
<div class="profile-next-links"><a href="/resources">ابزارهای رایگان</a><a href="/profile#community">عضویت جامعه در پروفایل</a><?php if($signup):?><a href="/feedback/toolbox">فایل نشست</a><?php endif;?></div>
<?php if($hallCodeEnabled && !$signup):?><details class="member-section"><summary>ورود با کد سالن (شرکت‌کنندگان قبلی)</summary><form class="member-section__body stack" method="post" action="/feedback/access"><?= csrf_field() ?><input type="hidden" name="event" value="<?= e($event['slug']) ?>"><label class="form-group"><span class="form-label">شماره موبایل ثبت‌شده</span><input class="form-control ltr" name="phone" type="tel" required></label><label class="form-group"><span class="form-label">کد سالن</span><input class="form-control ltr" name="access_code" required></label><button class="btn btn--secondary">ورود</button></form></details><?php endif;?>
</div></section>
