<?php
$copy = [
    'fa'=>['eyebrow'=>'بنیان‌گذار و مدیر آکادمی','bio'=>'بیوگرافی بنیان‌گذار','idea'=>'ایده شکل‌گیری منتوریس','work'=>'حوزه‌های فعالیت','areas'=>['پژوهش‌های روان‌شناختی','روش‌های کمی و شناختی','علوم شناختی و نورومدولاسیون','آموزش و توسعه مهارت‌های تخصصی'],'connect'=>'برای همکاری علمی و حرفه‌ای با ما در ارتباط باشید.'],
    'ar'=>['eyebrow'=>'المؤسِّسة ومديرة الأكاديمية','bio'=>'السيرة المهنية','idea'=>'فكرة منتوريس','work'=>'مجالات العمل','areas'=>['البحوث النفسية','المناهج الكمية والمعرفية','العلوم المعرفية والتعديل العصبي','التعليم وتنمية المهارات المتخصصة'],'connect'=>'تواصلوا معنا للتعاون العلمي والمهني.'],
    'ku'=>['eyebrow'=>'دامەزرێنەر و بەڕێوەبەری ئەکادیمی','bio'=>'ژیاننامەی پیشەیی','idea'=>'بیرۆکەی مێنتۆریس','work'=>'بوارەکانی کار','areas'=>['توێژینەوەی دەروونی','ڕێبازە ژمارەیی و مەعریفییەکان','زانستە مەعریفییەکان و نیورۆمۆدیولەیشن','فێرکردن و گەشەپێدانی توانای پسپۆڕی'],'connect'=>'بۆ هاوکاریی زانستی و پیشەیی پەیوەندیمان پێوە بکەن.'],
    'en'=>['eyebrow'=>'Founder & Academy Director','bio'=>'Founder biography','idea'=>'The idea behind Mentoris','work'=>'Areas of work','areas'=>['Psychological research','Quantitative and cognitive methods','Cognitive science and neuromodulation','Specialist education and skill development'],'connect'=>'Contact us to explore scientific and professional collaboration.'],
][locale()];
?>
<section class="founder-hero founder-hero--maryam"><div class="container founder-hero__grid">
    <figure class="founder-hero__portrait" data-reveal><img src="<?= asset($founder['image']) ?>" alt="<?= e($founder['name'] . '، ' . $founder['role']) ?>" width="1024" height="1536"></figure>
    <div class="founder-hero__content stack" data-reveal><span class="eyebrow"><?= e($copy['eyebrow']) ?></span><h1><?= e($founder['name']) ?></h1><p class="founder-role"><?= e($founder['role']) ?></p><p class="lead-copy"><?= e($founder['short_bio']) ?></p><div class="cluster"><a class="btn btn--primary" href="#biography"><?= e($copy['bio']) ?></a><a class="btn btn--ghost" href="/contact"><?= e(t('nav.contact')) ?></a></div></div>
</div></section>

<section class="section" id="biography"><div class="container founder-story-grid"><article class="founder-narrative stack" data-reveal><span class="eyebrow"><?= e($copy['bio']) ?></span><?php foreach ($founder['paragraphs'] as $index => $paragraph): ?><?php if ($index === 2): ?><h2><?= e($copy['idea']) ?></h2><?php endif; ?><p class="<?= $index === 0 ? 'lead-copy' : '' ?>"><?= e($paragraph) ?></p><?php endforeach; ?><blockquote>«<?= e($founder['quote']) ?>»</blockquote></article><aside class="founder-expertise surface" data-reveal><span class="eyebrow">Expertise</span><h2><?= e($copy['work']) ?></h2><ul class="check-list"><?php foreach ($copy['areas'] as $area): ?><li><?= e($area) ?></li><?php endforeach; ?></ul></aside></div></section>

<section class="section section--muted"><div class="container"><div class="public-cta"><span class="eyebrow">Collaboration</span><h2><?= e($copy['connect']) ?></h2><div class="cluster"><a class="btn btn--primary btn--lg" href="/contact"><?= e(t('nav.contact')) ?></a><a class="btn btn--ghost btn--lg ltr" href="mailto:Academichaghani@gmail.com">Academichaghani@gmail.com</a></div></div></div></section>
