<section class="founder-hero"><div class="container founder-hero__grid"><div class="founder-hero__portrait" data-reveal><img src="<?= asset('images/founder-fictional-v1.png') ?>" alt="پرتره نمایشی دکتر امیرحسین محمدی"><span class="founder-preview__note">شخصیت و تصویر نمایشی</span></div><div class="founder-hero__content stack" data-reveal><span class="eyebrow">Founder of Mentoris</span><h1>دکتر امیرحسین محمدی</h1><p class="founder-role">روان‌شناس، پژوهشگر و بنیان‌گذار آکادمی Mentoris</p><p>بیش از یک دهه فعالیت در آموزش، پژوهش و فضای حرفه‌ای، یک مسئله را روشن کرد: متخصصان برای رشد به چیزی فراتر از انتقال محتوا نیاز دارند؛ به تجربه‌ای منسجم، جامعه‌ای همراه و فضایی برای پرسیدن و آزمودن.</p><div class="cluster"><a class="btn btn--primary" href="/contact">دعوت به همکاری</a><a class="btn btn--ghost" href="#story">داستان Mentoris</a></div></div></div></section>

<section class="section section--muted" id="story"><div class="container founder-story"><div class="stack" data-reveal><span class="eyebrow">The Story</span><h2>چرا Mentoris شکل گرفت؟</h2><p>در بسیاری از مسیرهای آموزشی، دانش به‌صورت پراکنده و جدا از زمینه واقعی ارائه می‌شود. ایده Mentoris ساختن پلی میان علم، عمل و انسان بود؛ جایی که یادگیرنده فقط دریافت‌کننده محتوا نباشد، بلکه بخشی از یک جامعه پویا شود.</p><p>این آکادمی با رویکردی میان‌رشته‌ای طراحی شد تا روان‌شناسی، علوم اعصاب، توسعه فردی و مهارت‌های حرفه‌ای در یک تجربه منسجم کنار هم قرار بگیرند.</p></div><blockquote class="founder-quote" data-reveal>«هدف ما ساختن دوره‌های بیشتر نیست؛ ساختن تجربه‌هایی است که شیوه فکر کردن و عمل حرفه‌ای را تغییر دهند.»<cite>— بنیان‌گذار Mentoris</cite></blockquote></div></section>

<section class="section"><div class="container"><header class="section__head"><div><span class="eyebrow">Professional Path</span><h2>مسیر حرفه‌ای</h2></div></header><div class="timeline"><article><span>۱۳۹۳</span><div><h3>آغاز فعالیت تخصصی</h3><p>شروع پژوهش و آموزش در حوزه روان‌شناسی بالینی و سلامت روان.</p></div></article><article><span>۱۳۹۷</span><div><h3>توسعه برنامه‌های آموزشی</h3><p>طراحی کارگاه‌های کاربردی برای درمانگران و دانشجویان.</p></div></article><article><span>۱۴۰۱</span><div><h3>شکل‌گیری ایده Mentoris</h3><p>تعریف مدل یکپارچه آموزش، پژوهش و جامعه حرفه‌ای.</p></div></article><article><span>۱۴۰۵</span><div><h3>آغاز فصل تازه</h3><p>توسعه آکادمی به‌عنوان یک اکوسیستم یادگیری فارسی‌زبان.</p></div></article></div></div></section>

<section class="section section--muted"><div class="container"><header class="section__head"><div><span class="eyebrow">Focus Areas</span><h2>حوزه‌های تمرکز</h2></div></header><div class="grid grid--3"><article class="feature-card surface"><div class="feature-card__icon">Ψ</div><h3>روان‌شناسی بالینی</h3><p>رویکردهای درمانی و مهارت‌های حرفه‌ای.</p></article><article class="feature-card surface"><div class="feature-card__icon">⌁</div><h3>آموزش بزرگسالان</h3><p>طراحی تجربه یادگیری عمیق و پایدار.</p></article><article class="feature-card surface"><div class="feature-card__icon">◎</div><h3>توسعه اکوسیستم</h3><p>ساخت جامعه و شبکه همکاری متخصصان.</p></article></div></div></section>

<section class="section"><div class="container"><div class="public-cta"><h2>برای ساختن آینده‌ای اثرگذار همراه شوید</h2><p>پیشنهاد همکاری، پژوهش یا آموزش دارید؟ مستقیم با تیم Mentoris گفتگو کنید.</p><a class="btn btn--primary" href="/contact">شروع گفتگو</a></div></div></section>
