<section class="user-area"><div class="container user-layout"><?php require view_path('components/user/sidebar.php'); ?><div class="user-main"><header class="user-page-head"><div><span class="eyebrow">Account Settings</span><h1>پروفایل من</h1><p>اطلاعات فردی و حرفه‌ای حساب خود را مدیریت کنید.</p></div></header><div class="profile-grid"><section class="user-panel profile-form"><header><div><h2>اطلاعات حساب</h2><p>ایمیل حساب بعد از ثبت‌نام قابل تغییر نیست.</p></div></header><?php if ($success): ?><div class="alert alert--success" role="status"><strong>پروفایل شما به‌روزرسانی شد.</strong></div><?php endif; ?><?php if ($errors): ?><div class="alert alert--danger" role="alert"><strong>لطفاً اطلاعات فرم را بررسی کنید.</strong></div><?php endif; ?><form class="stack" method="post" action="/profile"><?= csrf_field() ?><label class="form-group"><span class="form-label">نام و نام خانوادگی</span><input class="form-control" name="name" value="<?= e($old['name'] ?? $user['name']) ?>" required><?php if (isset($errors['name'])): ?><span class="form-error"><?= e($errors['name'][0]) ?></span><?php endif; ?></label><label class="form-group"><span class="form-label">ایمیل</span><input class="form-control ltr" value="<?= e($user['email']) ?>" disabled><span class="form-hint">برای تغییر ایمیل با پشتیبانی تماس بگیرید.</span></label><div class="grid grid--2"><label class="form-group"><span class="form-label">شماره تماس</span><input class="form-control ltr" type="tel" name="phone" value="<?= e($old['phone'] ?? $user['phone']) ?>" required><?php if(isset($errors['phone'])):?><small class="form-error"><?= e($errors['phone'][0]) ?></small><?php endif;?></label></div><button class="btn btn--primary" type="submit">ذخیره تغییرات</button></form></section><aside class="profile-summary user-panel"><div class="profile-avatar"><?= e(mb_substr($user['name'], 0, 1)) ?></div><h2><?= e($user['name']) ?></h2><p><?= e($user['role'] ?: 'نقش حرفه‌ای ثبت نشده') ?></p><dl><div><dt>عضویت از</dt><dd><?= e(substr($user['created_at'], 0, 10)) ?></dd></div><div><dt>وضعیت حساب</dt><dd><span class="badge badge--success">فعال</span></dd></div></dl><small class="form-hint">برای تغییر رمز، ابتدا از حساب خارج شوید و از بازیابی رمز استفاده کنید.</small></aside></div><?php if(isset($_GET['welcome'])):?><div class="alert alert--success">حساب شما آماده است. اطلاعات تکمیلی را حالا یا بعداً ذخیره کنید.</div><?php endif;?><?php require view_path('components/user/member-form.php'); ?></div></div></section>
<?php
$therapist = $therapist ?? [];
$therapistErrors = $therapistErrors ?? [];
$choices = [
    'education_level' => ['masters_student'=>'دانشجوی ارشد','masters'=>'کارشناسی ارشد','phd_student'=>'دانشجوی دکتری','phd'=>'دکتری تخصصی'],
    'specialization' => ['clinical'=>'بالینی','health'=>'سلامت','general'=>'عمومی','counseling'=>'مشاوره','other'=>'سایر'],
    'experience' => ['under_1'=>'کمتر از ۱ سال','1_3'=>'۱ تا ۳ سال','3_7'=>'۳ تا ۷ سال','over_7'=>'بیش از ۷ سال'],
    'approaches' => ['ACT'=>'ACT','CBT'=>'CBT','schema'=>'طرحواره‌درمانی','psychodynamic'=>'روان‌پویشی','CFT'=>'متمرکز بر شفقت','other'=>'سایر'],
    'practice_areas' => ['adult'=>'فردی بزرگسال','trauma'=>'تروما','couples'=>'زوج','child'=>'کودک و نوجوان','other'=>'سایر'],
];
?>
<section class="section therapist-profile"><div class="container container--md"><details class="member-section"><summary>اطلاعات اختیاری صدور گواهی رویداد</summary><div class="user-panel"><header><div><span class="eyebrow">Professional Profile</span><h2>اطلاعات اختیاری صدور گواهی</h2><p>عضویت در سایت به رویداد وابسته نیست. این بخش را هر زمان خواستید تکمیل کنید؛ اطلاعات هویتی فقط برای بررسی گواهی احتمالی استفاده می‌شود.</p></div></header>
<?php if (!empty($therapistSuccess)): ?><div class="alert alert--success" role="status">اطلاعات تخصصی ذخیره شد.</div><?php endif; ?>
<?php if ($therapistErrors): ?><div class="alert alert--danger" role="alert">لطفاً فیلدهای مشخص‌شده را اصلاح کنید.</div><?php endif; ?>
<?php if (empty($therapistEnabled)): ?><div class="alert alert--danger" role="status">فرم تخصصی پس از اعمال ساختار جدید پایگاه داده فعال می‌شود.</div><?php else: ?><form class="stack" method="post" action="/profile/therapist"><?= csrf_field() ?>
<div class="grid grid--2">
<?php foreach (['latin_name'=>'نام انگلیسی','national_id'=>'کد ملی','professional_number'=>'شماره نظام / دانشجویی','university'=>'دانشگاه محل تحصیل'] as $field=>$label): ?><label class="form-group"><span class="form-label"><?= e($label) ?></span><input class="form-control <?= in_array($field, ['latin_name','national_id'], true) ? 'ltr' : '' ?>" name="<?= e($field) ?>" value="<?= e($therapist[$field] ?? '') ?>" maxlength="<?= $field === 'university' ? 160 : 120 ?>" <?= $field === 'national_id' ? 'inputmode="numeric"' : '' ?>><?php if (isset($therapistErrors[$field])): ?><small class="form-error"><?= e($therapistErrors[$field][0]) ?></small><?php endif; ?></label><?php endforeach; ?>
<?php foreach (['education_level'=>'مقطع تحصیلی','specialization'=>'گرایش تخصصی','experience'=>'سابقه کار بالینی'] as $field=>$label): ?><label class="form-group"><span class="form-label"><?= e($label) ?></span><select class="form-select" name="<?= e($field) ?>"><option value="">انتخاب کنید</option><?php foreach ($choices[$field] as $value=>$text): ?><option value="<?= e($value) ?>" <?= ($therapist[$field] ?? '') === $value ? 'selected' : '' ?>><?= e($text) ?></option><?php endforeach; ?></select><?php if (isset($therapistErrors[$field])): ?><small class="form-error"><?= e($therapistErrors[$field][0]) ?></small><?php endif; ?></label><?php endforeach; ?>
<label class="form-group"><span class="form-label">لینک اینستاگرام یا لینکدین</span><input class="form-control ltr" type="url" name="social_link" value="<?= e($therapist['social_link'] ?? '') ?>" maxlength="255" placeholder="https://..."><?php if (isset($therapistErrors['social_link'])): ?><small class="form-error"><?= e($therapistErrors['social_link'][0]) ?></small><?php endif; ?></label></div>
<?php foreach (['approaches'=>'رویکردهای درمانی','practice_areas'=>'حیطه‌های تخصصی'] as $field=>$label): ?><fieldset class="profile-choice"><legend><?= e($label) ?></legend><div class="profile-choice__grid"><?php foreach ($choices[$field] as $value=>$text): ?><label class="check"><input type="checkbox" name="<?= e($field) ?>[]" value="<?= e($value) ?>" <?= in_array($value, $therapist[$field] ?? [], true) ? 'checked' : '' ?>><span><?= e($text) ?></span></label><?php endforeach; ?></div><?php if (isset($therapistErrors[$field])): ?><small class="form-error"><?= e($therapistErrors[$field][0]) ?></small><?php endif; ?></fieldset><?php endforeach; ?>
<button class="btn btn--primary" type="submit">ذخیره پروفایل تخصصی</button></form><?php endif; ?></div></details></div></section>
