<?php $member=$member ?? []; $communityMembership=$communityMembership ?? (new \App\Repositories\EngagementRepository())->communityForUser($user); $communityOn=in_array($communityMembership['status'] ?? '',['pending','approved'],true); ?>
<section class="user-area user-area--profile"><div class="container user-layout"><?php require view_path('components/user/sidebar.php'); ?><div class="user-main">
<header class="profile-welcome"><div><span class="eyebrow">فضای شخصی شما</span><h1>سلام <?= e(explode(' ',$user['name'])[0]) ?>، خوش آمدید.</h1><p>حساب شما فعال است؛ اطلاعات تخصصی را هر زمان خواستید تکمیل کنید.</p></div><a class="btn btn--ghost btn--sm" href="/resources">ابزارهای رایگان <?= icon('arrow-left') ?></a><form method="post" action="/logout" class="profile-logout"><?= csrf_field() ?><button class="btn btn--ghost btn--sm">خروج</button></form></header>
<?php if(isset($_GET['welcome'])):?><div class="alert alert--success" role="status">عضویت شما انجام شد. همین‌جا می‌توانید پروفایل و درخواست عضویت جامعه را مدیریت کنید.</div><?php endif;?>
<section class="community-toggle-card user-panel" id="community"><div><span class="eyebrow">جامعهٔ حرفه‌ای منتوریس</span><h2>کنار هم رشد کنیم.</h2><p>برای ثبت درخواست عضویت، گزینهٔ زیر را فعال کنید. فرم دیگری لازم نیست.</p></div><form method="post" action="/profile/community" data-community-toggle><?= csrf_field() ?><label class="check"><input type="checkbox" name="requested" value="1" <?= $communityOn ? 'checked' : '' ?>><span>مایلم عضو جامعهٔ حرفه‌ای منتوریس شوم.</span></label><p data-community-status role="status" aria-live="polite"><?= e(['pending'=>'درخواست ثبت شده؛ در انتظار بررسی','approved'=>'عضویت شما تأیید شده است.','rejected'=>'برای بررسی درخواست با پشتیبانی تماس بگیرید.','suspended'=>'عضویت نیاز به بررسی پشتیبانی دارد.','withdrawn'=>'درخواست عضویت غیرفعال است.'][$communityMembership['status'] ?? ''] ?? 'عضویت اختیاری است.') ?></p><noscript><button class="btn btn--secondary">ذخیرهٔ انتخاب</button></noscript></form></section>
<?php require view_path('components/user/member-form.php'); ?>
<?php require view_path('components/user/phone-verification.php'); ?>
<details class="user-panel account-details" id="account-contact"><summary>اطلاعات حساب و شمارهٔ تماس</summary>
<?php if($success):?><div class="alert alert--success">اطلاعات حساب ذخیره شد.</div><?php endif;?><?php if($errors):?><div class="alert alert--danger"><?php foreach($errors as $messages):?><p><?= e($messages[0]) ?></p><?php endforeach;?></div><?php endif;?>
<form class="stack" method="post" action="/profile" data-async-save><?= csrf_field() ?><div class="grid grid--2"><label class="form-group"><span class="form-label">نام و نام خانوادگی</span><input class="form-control" name="name" maxlength="80" value="<?= e($old['name'] ?? $user['name']) ?>" required></label><label class="form-group"><span class="form-label">شماره موبایل</span><input class="form-control ltr" type="tel" name="phone" maxlength="20" value="<?= e($old['phone'] ?? $user['phone']) ?>" required></label></div><p class="form-hint">ایمیل حساب: <bdi><?= e($user['email']) ?></bdi></p><button class="btn btn--secondary" type="submit">ذخیره اطلاعات حساب</button><span data-save-status role="status"></span></form></details>
<div class="profile-next-links"><a href="/feedback">ثبت نظر دربارهٔ نشست‌ها <?= icon('arrow-left') ?></a><a href="/my-certificates">گواهی‌های من <?= icon('arrow-left') ?></a><a href="https://t.me/mentorisacademy_bot" target="_blank" rel="noopener">همراه تلگرامی منتوریس <?= icon('arrow-up-left') ?></a></div>
<?php require view_path('components/user/certificate-profile.php'); ?>
</div></div></section>
